// Generated by uniffi-bindgen-react-native
// Export the generated bindings to the app.
export * from './generated/livekit_uniffi';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as livekit_uniffi from './generated/livekit_uniffi';

import initAsync from './generated/wasm-bindgen/index.js';
import wasmPath from './generated/wasm-bindgen/index_bg.wasm';

export async function uniffiInitAsync() {
  await initAsync({ module_or_path: wasmPath })

  // Initialize the generated bindings: mostly checksums, but also callbacks.
  // - the boolean flag ensures this loads exactly once, even if the JS code
  //   is reloaded (e.g. during development with metro).
  livekit_uniffi.default.initialize();
}

// Export the crates as individually namespaced objects.
export default {
  livekit_uniffi,
};

