[package]
name = "webhooks"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
livekit-api = { workspace = true, features = ["rustls-tls-native-roots"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }