[package]
name = "webhooks"
version = "0.1.0"
edition = "2021"

[dependencies]
livekit-api = { workspace = true }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
