/*
 * Copyright 2025 LiveKit, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require("path");

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== "function") {
    try {
      const lddPath = require("child_process")
        .execSync("which ldd")
        .toString()
        .trim();
      return readFileSync(lddPath, "utf8").includes("musl");
    } catch (e) {
      return true;
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header;
    return !glibcVersionRuntime;
  }
}

switch (platform) {
  case "android":
    switch (arch) {
      case "arm64":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.android-arm64.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.android-arm64.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-android-arm64");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "arm":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.android-arm-eabi.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.android-arm-eabi.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-android-arm-eabi");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`);
    }
    break;
  case "win32":
    switch (arch) {
      case "x64":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.win32-x64-msvc.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.win32-x64-msvc.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-win32-x64-msvc");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "ia32":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.win32-ia32-msvc.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.win32-ia32-msvc.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-win32-ia32-msvc");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "arm64":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.win32-arm64-msvc.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.win32-arm64-msvc.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-win32-arm64-msvc");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  case "darwin":
    localFileExisted = existsSync(
      join(__dirname, "rtc-node.darwin-universal.node"),
    );
    try {
      if (localFileExisted) {
        nativeBinding = require("./rtc-node.darwin-universal.node");
      } else {
        nativeBinding = require("@livekit/rtc-ffi-bindings-darwin-universal");
      }
      break;
    } catch {}
    switch (arch) {
      case "x64":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.darwin-x64.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.darwin-x64.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-darwin-x64");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "arm64":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.darwin-arm64.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.darwin-arm64.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-darwin-arm64");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case "freebsd":
    if (arch !== "x64") {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`);
    }
    localFileExisted = existsSync(join(__dirname, "rtc-node.freebsd-x64.node"));
    try {
      if (localFileExisted) {
        nativeBinding = require("./rtc-node.freebsd-x64.node");
      } else {
        nativeBinding = require("@livekit/rtc-ffi-bindings-freebsd-x64");
      }
    } catch (e) {
      loadError = e;
    }
    break;
  case "linux":
    switch (arch) {
      case "x64":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-x64-musl.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-x64-musl.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-x64-musl");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-x64-gnu.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-x64-gnu.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-x64-gnu");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "arm64":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-arm64-musl.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-arm64-musl.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-arm64-musl");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-arm64-gnu.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-arm64-gnu.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-arm64-gnu");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "arm":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-arm-musleabihf.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-arm-musleabihf.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-arm-musleabihf");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-arm-gnueabihf.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-arm-gnueabihf.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-arm-gnueabihf");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "riscv64":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-riscv64-musl.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-riscv64-musl.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-riscv64-musl");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "rtc-node.linux-riscv64-gnu.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./rtc-node.linux-riscv64-gnu.node");
            } else {
              nativeBinding = require("@livekit/rtc-ffi-bindings-linux-riscv64-gnu");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "s390x":
        localFileExisted = existsSync(
          join(__dirname, "rtc-node.linux-s390x-gnu.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./rtc-node.linux-s390x-gnu.node");
          } else {
            nativeBinding = require("@livekit/rtc-ffi-bindings-linux-s390x-gnu");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(`Failed to load native binding`);
}

const {
  livekitInitialize,
  livekitFfiRequest,
  livekitRetrievePtr,
  livekitCopyBuffer,
  livekitDispose,
  FfiHandle,
} = nativeBinding;

module.exports.livekitInitialize = livekitInitialize;
module.exports.livekitFfiRequest = livekitFfiRequest;
module.exports.livekitRetrievePtr = livekitRetrievePtr;
module.exports.livekitCopyBuffer = livekitCopyBuffer;
module.exports.livekitDispose = livekitDispose;
module.exports.FfiHandle = FfiHandle;
