[package]
name = "stream-dump"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
env_logger = "0.11.8"
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
log = "0.4.28"