/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FfiHandle {
  constructor(handle: bigint)
  dispose(): void
  get handle(): bigint
}

export declare function livekitCopyBuffer(ptr: bigint, len: number): Uint8Array

export declare function livekitDispose(): Promise<void>

export declare function livekitFfiRequest(data: Uint8Array): Uint8Array

export declare function livekitInitialize(callback: (data: Uint8Array) => void, captureLogs: boolean, sdkVersion: string): void

export declare function livekitRetrievePtr(handle: Uint8Array): bigint
