---
rust:
  directory: ../livekit-uniffi
  manifestPath: Cargo.toml

web:
  entrypoint: src/OUTPUT.ts

# ---
# rust:
#   repo: https://github.com/jhugman/uniffi-starter.git
#   branch: jhugman/bump-uniffi-to-0.29
#   manifestPath: rust/foobar/Cargo.toml
