// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file capture.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto2 } from "@bufbuild/protobuf";
import type { OwnedVideoSource, VideoCodec, VideoSourceResolution } from "./video_frame_pb.js";
import type { TrackPublishOptions } from "./room_pb.js";
import type { FfiOwnedHandle } from "./handle_pb.js";

/**
 * Test patterns built into livekit-capture.
 *
 * @generated from enum livekit.proto.Pattern
 */
export declare enum Pattern {
  /**
   * Animated color gradient.
   *
   * @generated from enum value: PATTERN_GRADIENT = 0;
   */
  GRADIENT = 0,

  /**
   * Bouncing LiveKit logo.
   *
   * @generated from enum value: PATTERN_LOGO = 1;
   */
  LOGO = 1,
}

/**
 * Kind of media a capture source produces.
 *
 * @generated from enum livekit.proto.CaptureSourceKind
 */
export declare enum CaptureSourceKind {
  /**
   * Pixel frames, published through the WebRTC encoder.
   *
   * @generated from enum value: CAPTURE_SOURCE_PIXEL = 0;
   */
  CAPTURE_SOURCE_PIXEL = 0,

  /**
   * Pre-encoded access units, published as passthrough.
   *
   * @generated from enum value: CAPTURE_SOURCE_ENCODED = 1;
   */
  CAPTURE_SOURCE_ENCODED = 1,
}

/**
 * Why a capture ended without error.
 *
 * @generated from enum livekit.proto.CaptureExit
 */
export declare enum CaptureExit {
  /**
   * Stopped by StopCaptureRequest (or handle disposal).
   *
   * @generated from enum value: CAPTURE_EXIT_STOPPED = 0;
   */
  STOPPED = 0,

  /**
   * The producer reached the end of its stream.
   *
   * @generated from enum value: CAPTURE_EXIT_END_OF_STREAM = 1;
   */
  END_OF_STREAM = 1,
}

/**
 * Test pattern rendered on the GPU.
 *
 * @generated from message livekit.proto.PatternVideoSourceConfig
 */
export declare class PatternVideoSourceConfig extends Message<PatternVideoSourceConfig> {
  /**
   * Output resolution.
   *
   * @generated from field: required livekit.proto.VideoSourceResolution resolution = 1;
   */
  resolution?: VideoSourceResolution;

  /**
   * Output frame rate in frames per second.
   *
   * @generated from field: required uint32 framerate_fps = 2;
   */
  framerateFps?: number;

  /**
   * Pattern to render.
   *
   * @generated from field: required livekit.proto.Pattern pattern = 3;
   */
  pattern?: Pattern;

  constructor(data?: PartialMessage<PatternVideoSourceConfig>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.PatternVideoSourceConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PatternVideoSourceConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PatternVideoSourceConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PatternVideoSourceConfig;

  static equals(a: PatternVideoSourceConfig | PlainMessage<PatternVideoSourceConfig> | undefined, b: PatternVideoSourceConfig | PlainMessage<PatternVideoSourceConfig> | undefined): boolean;
}

/**
 * Wall clock with millisecond precision, rendered on the GPU. Shows the
 * local time of the machine that runs the FFI server.
 *
 * @generated from message livekit.proto.ClockVideoSourceConfig
 */
export declare class ClockVideoSourceConfig extends Message<ClockVideoSourceConfig> {
  /**
   * Output resolution.
   *
   * @generated from field: required livekit.proto.VideoSourceResolution resolution = 1;
   */
  resolution?: VideoSourceResolution;

  /**
   * Output frame rate in frames per second.
   *
   * @generated from field: required uint32 framerate_fps = 2;
   */
  framerateFps?: number;

  constructor(data?: PartialMessage<ClockVideoSourceConfig>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.ClockVideoSourceConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClockVideoSourceConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClockVideoSourceConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClockVideoSourceConfig;

  static equals(a: ClockVideoSourceConfig | PlainMessage<ClockVideoSourceConfig> | undefined, b: ClockVideoSourceConfig | PlainMessage<ClockVideoSourceConfig> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.CaptureSourceInfo
 */
export declare class CaptureSourceInfo extends Message<CaptureSourceInfo> {
  /**
   * @generated from field: required livekit.proto.CaptureSourceKind kind = 1;
   */
  kind?: CaptureSourceKind;

  /**
   * Declared or discovered stream resolution.
   *
   * @generated from field: required livekit.proto.VideoSourceResolution resolution = 2;
   */
  resolution?: VideoSourceResolution;

  /**
   * Codec produced by the source; encoded sources only.
   *
   * @generated from field: optional livekit.proto.VideoCodec codec = 3;
   */
  codec?: VideoCodec;

  /**
   * Publish options derived from the source (codec, encoder backend, ...).
   * Merge application options (e.g. track source) over these when calling
   * PublishTrackRequest.
   *
   * @generated from field: required livekit.proto.TrackPublishOptions recommended_publish_options = 4;
   */
  recommendedPublishOptions?: TrackPublishOptions;

  /**
   * RTC video source fed by this capture source; pass its handle to
   * CreateVideoTrackRequest. Owned by the client like any other handle.
   *
   * @generated from field: required livekit.proto.OwnedVideoSource video_source = 5;
   */
  videoSource?: OwnedVideoSource;

  constructor(data?: PartialMessage<CaptureSourceInfo>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureSourceInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureSourceInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureSourceInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureSourceInfo;

  static equals(a: CaptureSourceInfo | PlainMessage<CaptureSourceInfo> | undefined, b: CaptureSourceInfo | PlainMessage<CaptureSourceInfo> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.OwnedCaptureSource
 */
export declare class OwnedCaptureSource extends Message<OwnedCaptureSource> {
  /**
   * @generated from field: required livekit.proto.FfiOwnedHandle handle = 1;
   */
  handle?: FfiOwnedHandle;

  /**
   * @generated from field: required livekit.proto.CaptureSourceInfo info = 2;
   */
  info?: CaptureSourceInfo;

  constructor(data?: PartialMessage<OwnedCaptureSource>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.OwnedCaptureSource";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnedCaptureSource;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnedCaptureSource;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnedCaptureSource;

  static equals(a: OwnedCaptureSource | PlainMessage<OwnedCaptureSource> | undefined, b: OwnedCaptureSource | PlainMessage<OwnedCaptureSource> | undefined): boolean;
}

/**
 * Create a new capture source from configuration.
 *
 * Completes asynchronously with a NewCaptureSourceCallback: construction
 * starts the producer and may wait for its first output to discover stream
 * settings.
 *
 * @generated from message livekit.proto.NewCaptureSourceRequest
 */
export declare class NewCaptureSourceRequest extends Message<NewCaptureSourceRequest> {
  /**
   * @generated from oneof livekit.proto.NewCaptureSourceRequest.config
   */
  config: {
    /**
     * @generated from field: livekit.proto.PatternVideoSourceConfig pattern = 2;
     */
    value: PatternVideoSourceConfig;
    case: "pattern";
  } | {
    /**
     * @generated from field: livekit.proto.ClockVideoSourceConfig clock = 5;
     */
    value: ClockVideoSourceConfig;
    case: "clock";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: optional uint64 request_async_id = 3;
   */
  requestAsyncId?: bigint;

  constructor(data?: PartialMessage<NewCaptureSourceRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.NewCaptureSourceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NewCaptureSourceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NewCaptureSourceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NewCaptureSourceRequest;

  static equals(a: NewCaptureSourceRequest | PlainMessage<NewCaptureSourceRequest> | undefined, b: NewCaptureSourceRequest | PlainMessage<NewCaptureSourceRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.NewCaptureSourceResponse
 */
export declare class NewCaptureSourceResponse extends Message<NewCaptureSourceResponse> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  constructor(data?: PartialMessage<NewCaptureSourceResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.NewCaptureSourceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NewCaptureSourceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NewCaptureSourceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NewCaptureSourceResponse;

  static equals(a: NewCaptureSourceResponse | PlainMessage<NewCaptureSourceResponse> | undefined, b: NewCaptureSourceResponse | PlainMessage<NewCaptureSourceResponse> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.NewCaptureSourceCallback
 */
export declare class NewCaptureSourceCallback extends Message<NewCaptureSourceCallback> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  /**
   * @generated from oneof livekit.proto.NewCaptureSourceCallback.message
   */
  message: {
    /**
     * @generated from field: string error = 2;
     */
    value: string;
    case: "error";
  } | {
    /**
     * @generated from field: livekit.proto.OwnedCaptureSource source = 3;
     */
    value: OwnedCaptureSource;
    case: "source";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<NewCaptureSourceCallback>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.NewCaptureSourceCallback";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NewCaptureSourceCallback;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NewCaptureSourceCallback;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NewCaptureSourceCallback;

  static equals(a: NewCaptureSourceCallback | PlainMessage<NewCaptureSourceCallback> | undefined, b: NewCaptureSourceCallback | PlainMessage<NewCaptureSourceCallback> | undefined): boolean;
}

/**
 * Start pumping frames from a capture source into its RTC video source.
 *
 * @generated from message livekit.proto.StartCaptureRequest
 */
export declare class StartCaptureRequest extends Message<StartCaptureRequest> {
  /**
   * @generated from field: required uint64 capture_handle = 1;
   */
  captureHandle?: bigint;

  constructor(data?: PartialMessage<StartCaptureRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StartCaptureRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartCaptureRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartCaptureRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartCaptureRequest;

  static equals(a: StartCaptureRequest | PlainMessage<StartCaptureRequest> | undefined, b: StartCaptureRequest | PlainMessage<StartCaptureRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.StartCaptureResponse
 */
export declare class StartCaptureResponse extends Message<StartCaptureResponse> {
  /**
   * @generated from field: optional string error = 1;
   */
  error?: string;

  constructor(data?: PartialMessage<StartCaptureResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StartCaptureResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartCaptureResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartCaptureResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartCaptureResponse;

  static equals(a: StartCaptureResponse | PlainMessage<StartCaptureResponse> | undefined, b: StartCaptureResponse | PlainMessage<StartCaptureResponse> | undefined): boolean;
}

/**
 * Signal a running capture to stop after the frame in flight. The terminal
 * CaptureSourceEvent follows shortly. Stopping an already-finished capture
 * is a no-op.
 *
 * @generated from message livekit.proto.StopCaptureRequest
 */
export declare class StopCaptureRequest extends Message<StopCaptureRequest> {
  /**
   * @generated from field: required uint64 capture_handle = 1;
   */
  captureHandle?: bigint;

  constructor(data?: PartialMessage<StopCaptureRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StopCaptureRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopCaptureRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopCaptureRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopCaptureRequest;

  static equals(a: StopCaptureRequest | PlainMessage<StopCaptureRequest> | undefined, b: StopCaptureRequest | PlainMessage<StopCaptureRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.StopCaptureResponse
 */
export declare class StopCaptureResponse extends Message<StopCaptureResponse> {
  /**
   * @generated from field: optional string error = 1;
   */
  error?: string;

  constructor(data?: PartialMessage<StopCaptureResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StopCaptureResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopCaptureResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopCaptureResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopCaptureResponse;

  static equals(a: StopCaptureResponse | PlainMessage<StopCaptureResponse> | undefined, b: StopCaptureResponse | PlainMessage<StopCaptureResponse> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.CaptureFinished
 */
export declare class CaptureFinished extends Message<CaptureFinished> {
  /**
   * @generated from field: required uint64 frames_captured = 1;
   */
  framesCaptured?: bigint;

  /**
   * @generated from field: required livekit.proto.CaptureExit exit = 2;
   */
  exit?: CaptureExit;

  constructor(data?: PartialMessage<CaptureFinished>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureFinished";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureFinished;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureFinished;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureFinished;

  static equals(a: CaptureFinished | PlainMessage<CaptureFinished> | undefined, b: CaptureFinished | PlainMessage<CaptureFinished> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.CaptureError
 */
export declare class CaptureError extends Message<CaptureError> {
  /**
   * @generated from field: required string error = 1;
   */
  error?: string;

  constructor(data?: PartialMessage<CaptureError>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureError;

  static equals(a: CaptureError | PlainMessage<CaptureError> | undefined, b: CaptureError | PlainMessage<CaptureError> | undefined): boolean;
}

/**
 * Delivered exactly once when a started capture ends, regardless of why
 * (stop request, end of stream, or failure).
 *
 * @generated from message livekit.proto.CaptureSourceEvent
 */
export declare class CaptureSourceEvent extends Message<CaptureSourceEvent> {
  /**
   * @generated from field: required uint64 capture_handle = 1;
   */
  captureHandle?: bigint;

  /**
   * @generated from oneof livekit.proto.CaptureSourceEvent.message
   */
  message: {
    /**
     * @generated from field: livekit.proto.CaptureFinished finished = 2;
     */
    value: CaptureFinished;
    case: "finished";
  } | {
    /**
     * @generated from field: livekit.proto.CaptureError error = 3;
     */
    value: CaptureError;
    case: "error";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<CaptureSourceEvent>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureSourceEvent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureSourceEvent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureSourceEvent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureSourceEvent;

  static equals(a: CaptureSourceEvent | PlainMessage<CaptureSourceEvent> | undefined, b: CaptureSourceEvent | PlainMessage<CaptureSourceEvent> | undefined): boolean;
}

