// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file capture.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { proto2 } = require("@bufbuild/protobuf");
const { OwnedVideoSource, VideoCodec, VideoSourceResolution } = require("./video_frame_pb.js");
const { TrackPublishOptions } = require("./room_pb.js");
const { FfiOwnedHandle } = require("./handle_pb.js");

/**
 * Kind of media a capture source produces.
 *
 * @generated from enum livekit.proto.CaptureSourceKind
 */
const CaptureSourceKind = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.CaptureSourceKind",
  [
    {no: 0, name: "CAPTURE_SOURCE_PIXEL"},
    {no: 1, name: "CAPTURE_SOURCE_ENCODED"},
  ],
);

/**
 * Why a capture ended without error.
 *
 * @generated from enum livekit.proto.CaptureExit
 */
const CaptureExit = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.CaptureExit",
  [
    {no: 0, name: "CAPTURE_EXIT_STOPPED", localName: "STOPPED"},
    {no: 1, name: "CAPTURE_EXIT_END_OF_STREAM", localName: "END_OF_STREAM"},
  ],
);

/**
 * @generated from message livekit.proto.CaptureSourceInfo
 */
const CaptureSourceInfo = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.CaptureSourceInfo",
  () => [
    { no: 1, name: "kind", kind: "enum", T: proto2.getEnumType(CaptureSourceKind), req: true },
    { no: 2, name: "resolution", kind: "message", T: VideoSourceResolution, req: true },
    { no: 3, name: "codec", kind: "enum", T: proto2.getEnumType(VideoCodec), opt: true },
    { no: 4, name: "recommended_publish_options", kind: "message", T: TrackPublishOptions, req: true },
    { no: 5, name: "video_source", kind: "message", T: OwnedVideoSource, req: true },
  ],
);

/**
 * @generated from message livekit.proto.OwnedCaptureSource
 */
const OwnedCaptureSource = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.OwnedCaptureSource",
  () => [
    { no: 1, name: "handle", kind: "message", T: FfiOwnedHandle, req: true },
    { no: 2, name: "info", kind: "message", T: CaptureSourceInfo, req: true },
  ],
);

/**
 * Start pumping frames from a capture source into its RTC video source.
 *
 * @generated from message livekit.proto.StartCaptureRequest
 */
const StartCaptureRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.StartCaptureRequest",
  () => [
    { no: 1, name: "capture_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.StartCaptureResponse
 */
const StartCaptureResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.StartCaptureResponse",
  () => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * Signal a running capture to stop after the frame in flight. The terminal
 * CaptureSourceEvent follows shortly. Stopping an already-finished capture
 * is a no-op.
 *
 * @generated from message livekit.proto.StopCaptureRequest
 */
const StopCaptureRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.StopCaptureRequest",
  () => [
    { no: 1, name: "capture_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.StopCaptureResponse
 */
const StopCaptureResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.StopCaptureResponse",
  () => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.CaptureFinished
 */
const CaptureFinished = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.CaptureFinished",
  () => [
    { no: 1, name: "frames_captured", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "exit", kind: "enum", T: proto2.getEnumType(CaptureExit), req: true },
  ],
);

/**
 * @generated from message livekit.proto.CaptureError
 */
const CaptureError = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.CaptureError",
  () => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * Delivered exactly once when a started capture ends, regardless of why
 * (stop request, end of stream, or failure).
 *
 * @generated from message livekit.proto.CaptureSourceEvent
 */
const CaptureSourceEvent = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.CaptureSourceEvent",
  () => [
    { no: 1, name: "capture_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "finished", kind: "message", T: CaptureFinished, oneof: "message" },
    { no: 3, name: "error", kind: "message", T: CaptureError, oneof: "message" },
  ],
);


exports.CaptureSourceKind = CaptureSourceKind;
exports.CaptureExit = CaptureExit;
exports.CaptureSourceInfo = CaptureSourceInfo;
exports.OwnedCaptureSource = OwnedCaptureSource;
exports.StartCaptureRequest = StartCaptureRequest;
exports.StartCaptureResponse = StartCaptureResponse;
exports.StopCaptureRequest = StopCaptureRequest;
exports.StopCaptureResponse = StopCaptureResponse;
exports.CaptureFinished = CaptureFinished;
exports.CaptureError = CaptureError;
exports.CaptureSourceEvent = CaptureSourceEvent;
