// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file capture.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto2 } from "@bufbuild/protobuf";
import type { OwnedVideoSource, VideoCodec, VideoSourceResolution } from "./video_frame_pb.js";
import type { TrackPublishOptions } from "./room_pb.js";
import type { FfiOwnedHandle } from "./handle_pb.js";

/**
 * Bitrate unit expected by a GStreamer encoder property.
 *
 * @generated from enum livekit.proto.GstreamerBitrateUnit
 */
export declare enum GstreamerBitrateUnit {
  /**
   * @generated from enum value: GSTREAMER_BITRATE_UNIT_BPS = 0;
   */
  BPS = 0,

  /**
   * @generated from enum value: GSTREAMER_BITRATE_UNIT_KBPS = 1;
   */
  KBPS = 1,
}

/**
 * Test patterns built into livekit-capture.
 *
 * @generated from enum livekit.proto.Pattern
 */
export declare enum Pattern {
  /**
   * Animated color gradient.
   *
   * @generated from enum value: PATTERN_GRADIENT = 0;
   */
  GRADIENT = 0,

  /**
   * Bouncing LiveKit logo.
   *
   * @generated from enum value: PATTERN_LOGO = 1;
   */
  LOGO = 1,
}

/**
 * Frame format delivered by a capture device.
 *
 * @generated from enum livekit.proto.DeviceFrameFormat
 */
export declare enum DeviceFrameFormat {
  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_I420 = 0;
   */
  I420 = 0,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_NV12 = 1;
   */
  NV12 = 1,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_BGRA = 2;
   */
  BGRA = 2,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_RGB24 = 3;
   */
  RGB24 = 3,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_BGR24 = 4;
   */
  BGR24 = 4,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_YUYV = 5;
   */
  YUYV = 5,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_UYVY = 6;
   */
  UYVY = 6,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_GREY = 7;
   */
  GREY = 7,

  /**
   * @generated from enum value: DEVICE_FRAME_FORMAT_MJPEG = 8;
   */
  MJPEG = 8,
}

/**
 * Kind of media a capture source produces.
 *
 * @generated from enum livekit.proto.CaptureSourceKind
 */
export declare enum CaptureSourceKind {
  /**
   * Pixel frames, published through the WebRTC encoder.
   *
   * @generated from enum value: CAPTURE_SOURCE_PIXEL = 0;
   */
  CAPTURE_SOURCE_PIXEL = 0,

  /**
   * Pre-encoded access units, published as passthrough.
   *
   * @generated from enum value: CAPTURE_SOURCE_ENCODED = 1;
   */
  CAPTURE_SOURCE_ENCODED = 1,
}

/**
 * Why a capture ended without error.
 *
 * @generated from enum livekit.proto.CaptureExit
 */
export declare enum CaptureExit {
  /**
   * Stopped by StopCaptureRequest (or handle disposal).
   *
   * @generated from enum value: CAPTURE_EXIT_STOPPED = 0;
   */
  STOPPED = 0,

  /**
   * The producer reached the end of its stream.
   *
   * @generated from enum value: CAPTURE_EXIT_END_OF_STREAM = 1;
   */
  END_OF_STREAM = 1,
}

/**
 * Binding from WebRTC rate-control targets to a GStreamer encoder property.
 *
 * @generated from message livekit.proto.GstreamerRateControl
 */
export declare class GstreamerRateControl extends Message<GstreamerRateControl> {
  /**
   * Name of the encoder element in the pipeline (e.g. `lk_encoder`).
   *
   * @generated from field: required string element = 1;
   */
  element?: string;

  /**
   * Bitrate property to set on the element (e.g. `bitrate` for x264enc,
   * `target-bitrate` for vp8enc/vp9enc).
   *
   * @generated from field: required string property = 2;
   */
  property?: string;

  /**
   * Unit the property expects.
   *
   * @generated from field: required livekit.proto.GstreamerBitrateUnit unit = 3;
   */
  unit?: GstreamerBitrateUnit;

  constructor(data?: PartialMessage<GstreamerRateControl>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.GstreamerRateControl";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GstreamerRateControl;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GstreamerRateControl;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GstreamerRateControl;

  static equals(a: GstreamerRateControl | PlainMessage<GstreamerRateControl> | undefined, b: GstreamerRateControl | PlainMessage<GstreamerRateControl> | undefined): boolean;
}

/**
 * Encoded ingest from a GStreamer pipeline.
 *
 * @generated from message livekit.proto.GstreamerVideoSourceConfig
 */
export declare class GstreamerVideoSourceConfig extends Message<GstreamerVideoSourceConfig> {
  /**
   * GStreamer launch description for the encoded producer pipeline.
   * Must contain `appsink name=lk_appsink`, or leave exactly one encoded
   * video source pad unlinked for the source to attach one to.
   *
   * @generated from field: required string pipeline = 1;
   */
  pipeline?: string;

  /**
   * Codec expected from the pipeline; inferred from pipeline caps when
   * omitted.
   *
   * @generated from field: optional livekit.proto.VideoCodec codec = 2;
   */
  codec?: VideoCodec;

  /**
   * Encoded frame resolution. When omitted, it is discovered from the
   * pipeline's negotiated caps; when set, the pipeline output is verified
   * against it.
   *
   * @generated from field: optional livekit.proto.VideoSourceResolution resolution = 3;
   */
  resolution?: VideoSourceResolution;

  /**
   * Forwards WebRTC rate-control targets to an encoder element's bitrate
   * property. Without this, the pipeline encodes at a fixed bitrate.
   *
   * @generated from field: optional livekit.proto.GstreamerRateControl rate_control = 4;
   */
  rateControl?: GstreamerRateControl;

  constructor(data?: PartialMessage<GstreamerVideoSourceConfig>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.GstreamerVideoSourceConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GstreamerVideoSourceConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GstreamerVideoSourceConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GstreamerVideoSourceConfig;

  static equals(a: GstreamerVideoSourceConfig | PlainMessage<GstreamerVideoSourceConfig> | undefined, b: GstreamerVideoSourceConfig | PlainMessage<GstreamerVideoSourceConfig> | undefined): boolean;
}

/**
 * Encoded ingest from an RTSP server over TCP-interleaved RTP.
 *
 * @generated from message livekit.proto.RtspVideoSourceConfig
 */
export declare class RtspVideoSourceConfig extends Message<RtspVideoSourceConfig> {
  /**
   * RTSP URL (rtsp://host[:port]/path, or rtsps:// when the server is built
   * with TLS support). URL userinfo is accepted and stripped from requests;
   * `username`/`password` take precedence over it.
   *
   * @generated from field: required string url = 1;
   */
  url?: string;

  /**
   * Username for RTSP authentication, overriding URL userinfo.
   *
   * @generated from field: optional string username = 2;
   */
  username?: string;

  /**
   * Password for RTSP authentication, overriding URL userinfo.
   *
   * @generated from field: optional string password = 3;
   */
  password?: string;

  /**
   * Codec required from the stream; the first supported video track offered
   * by the SDP is used when omitted.
   *
   * @generated from field: optional livekit.proto.VideoCodec codec = 4;
   */
  codec?: VideoCodec;

  /**
   * Encoded frame resolution. When omitted, it is discovered from the SDP
   * when declared there, and from the stream's first keyframe otherwise;
   * when set, the first keyframe is verified against it.
   *
   * @generated from field: optional livekit.proto.VideoSourceResolution resolution = 5;
   */
  resolution?: VideoSourceResolution;

  /**
   * TCP connect and RTSP handshake timeout in milliseconds (default 10000).
   *
   * @generated from field: optional uint32 connect_timeout_ms = 6;
   */
  connectTimeoutMs?: number;

  /**
   * Maximum tolerated stream silence in milliseconds (default 30000).
   *
   * @generated from field: optional uint32 idle_timeout_ms = 7;
   */
  idleTimeoutMs?: number;

  /**
   * Disables TLS certificate verification for rtsps:// URLs. Most cameras
   * present self-signed certificates, which fail verification against the
   * system roots. The connection stays encrypted but is not authenticated:
   * a network attacker could impersonate the camera.
   *
   * @generated from field: optional bool accept_invalid_tls_certs = 8;
   */
  acceptInvalidTlsCerts?: boolean;

  constructor(data?: PartialMessage<RtspVideoSourceConfig>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.RtspVideoSourceConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RtspVideoSourceConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RtspVideoSourceConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RtspVideoSourceConfig;

  static equals(a: RtspVideoSourceConfig | PlainMessage<RtspVideoSourceConfig> | undefined, b: RtspVideoSourceConfig | PlainMessage<RtspVideoSourceConfig> | undefined): boolean;
}

/**
 * Test pattern rendered on the GPU.
 *
 * @generated from message livekit.proto.PatternVideoSourceConfig
 */
export declare class PatternVideoSourceConfig extends Message<PatternVideoSourceConfig> {
  /**
   * Output resolution.
   *
   * @generated from field: required livekit.proto.VideoSourceResolution resolution = 1;
   */
  resolution?: VideoSourceResolution;

  /**
   * Output frame rate in frames per second.
   *
   * @generated from field: required uint32 framerate_fps = 2;
   */
  framerateFps?: number;

  /**
   * Pattern to render.
   *
   * @generated from field: required livekit.proto.Pattern pattern = 3;
   */
  pattern?: Pattern;

  constructor(data?: PartialMessage<PatternVideoSourceConfig>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.PatternVideoSourceConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PatternVideoSourceConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PatternVideoSourceConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PatternVideoSourceConfig;

  static equals(a: PatternVideoSourceConfig | PlainMessage<PatternVideoSourceConfig> | undefined, b: PatternVideoSourceConfig | PlainMessage<PatternVideoSourceConfig> | undefined): boolean;
}

/**
 * Wall clock with millisecond precision, rendered on the GPU. Shows the
 * local time of the machine that runs the FFI server.
 *
 * @generated from message livekit.proto.ClockVideoSourceConfig
 */
export declare class ClockVideoSourceConfig extends Message<ClockVideoSourceConfig> {
  /**
   * Output resolution.
   *
   * @generated from field: required livekit.proto.VideoSourceResolution resolution = 1;
   */
  resolution?: VideoSourceResolution;

  /**
   * Output frame rate in frames per second.
   *
   * @generated from field: required uint32 framerate_fps = 2;
   */
  framerateFps?: number;

  constructor(data?: PartialMessage<ClockVideoSourceConfig>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.ClockVideoSourceConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClockVideoSourceConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClockVideoSourceConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClockVideoSourceConfig;

  static equals(a: ClockVideoSourceConfig | PlainMessage<ClockVideoSourceConfig> | undefined, b: ClockVideoSourceConfig | PlainMessage<ClockVideoSourceConfig> | undefined): boolean;
}

/**
 * Capture format offered by or requested from a device.
 *
 * @generated from message livekit.proto.DeviceFormat
 */
export declare class DeviceFormat extends Message<DeviceFormat> {
  /**
   * Frame dimensions.
   *
   * @generated from field: required livekit.proto.VideoSourceResolution resolution = 1;
   */
  resolution?: VideoSourceResolution;

  /**
   * Frame rate in frames per second.
   *
   * @generated from field: required uint32 framerate_fps = 2;
   */
  framerateFps?: number;

  /**
   * Frame format.
   *
   * @generated from field: required livekit.proto.DeviceFrameFormat frame_format = 3;
   */
  frameFormat?: DeviceFrameFormat;

  constructor(data?: PartialMessage<DeviceFormat>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DeviceFormat";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeviceFormat;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeviceFormat;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeviceFormat;

  static equals(a: DeviceFormat | PlainMessage<DeviceFormat> | undefined, b: DeviceFormat | PlainMessage<DeviceFormat> | undefined): boolean;
}

/**
 * Format selection requested from a capture device. The device negotiates
 * the delivered format; CaptureSourceInfo reports the outcome.
 *
 * @generated from message livekit.proto.DeviceFormatRequest
 */
export declare class DeviceFormatRequest extends Message<DeviceFormatRequest> {
  /**
   * The device's default format when unset.
   *
   * @generated from oneof livekit.proto.DeviceFormatRequest.request
   */
  request: {
    /**
     * Require an exact format match.
     *
     * @generated from field: livekit.proto.DeviceFormat exact = 1;
     */
    value: DeviceFormat;
    case: "exact";
  } | {
    /**
     * Use the device's closest supported format.
     *
     * @generated from field: livekit.proto.DeviceFormat closest = 2;
     */
    value: DeviceFormat;
    case: "closest";
  } | {
    /**
     * @generated from field: livekit.proto.DeviceFormatRequest.HighestFramerate highest_framerate = 3;
     */
    value: DeviceFormatRequest_HighestFramerate;
    case: "highestFramerate";
  } | {
    /**
     * @generated from field: livekit.proto.DeviceFormatRequest.HighestResolution highest_resolution = 4;
     */
    value: DeviceFormatRequest_HighestResolution;
    case: "highestResolution";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<DeviceFormatRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DeviceFormatRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeviceFormatRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeviceFormatRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeviceFormatRequest;

  static equals(a: DeviceFormatRequest | PlainMessage<DeviceFormatRequest> | undefined, b: DeviceFormatRequest | PlainMessage<DeviceFormatRequest> | undefined): boolean;
}

/**
 * Prefer the highest frame rate, optionally constrained.
 *
 * @generated from message livekit.proto.DeviceFormatRequest.HighestFramerate
 */
export declare class DeviceFormatRequest_HighestFramerate extends Message<DeviceFormatRequest_HighestFramerate> {
  /**
   * @generated from field: optional livekit.proto.VideoSourceResolution resolution = 1;
   */
  resolution?: VideoSourceResolution;

  /**
   * @generated from field: optional livekit.proto.DeviceFrameFormat frame_format = 2;
   */
  frameFormat?: DeviceFrameFormat;

  constructor(data?: PartialMessage<DeviceFormatRequest_HighestFramerate>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DeviceFormatRequest.HighestFramerate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeviceFormatRequest_HighestFramerate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeviceFormatRequest_HighestFramerate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeviceFormatRequest_HighestFramerate;

  static equals(a: DeviceFormatRequest_HighestFramerate | PlainMessage<DeviceFormatRequest_HighestFramerate> | undefined, b: DeviceFormatRequest_HighestFramerate | PlainMessage<DeviceFormatRequest_HighestFramerate> | undefined): boolean;
}

/**
 * Prefer the highest resolution, optionally constrained.
 *
 * @generated from message livekit.proto.DeviceFormatRequest.HighestResolution
 */
export declare class DeviceFormatRequest_HighestResolution extends Message<DeviceFormatRequest_HighestResolution> {
  /**
   * @generated from field: optional uint32 framerate_fps = 1;
   */
  framerateFps?: number;

  /**
   * @generated from field: optional livekit.proto.DeviceFrameFormat frame_format = 2;
   */
  frameFormat?: DeviceFrameFormat;

  constructor(data?: PartialMessage<DeviceFormatRequest_HighestResolution>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DeviceFormatRequest.HighestResolution";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeviceFormatRequest_HighestResolution;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeviceFormatRequest_HighestResolution;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeviceFormatRequest_HighestResolution;

  static equals(a: DeviceFormatRequest_HighestResolution | PlainMessage<DeviceFormatRequest_HighestResolution> | undefined, b: DeviceFormatRequest_HighestResolution | PlainMessage<DeviceFormatRequest_HighestResolution> | undefined): boolean;
}

/**
 * Camera device capture using the platform's native capture stack.
 *
 * @generated from message livekit.proto.DeviceVideoSourceConfig
 */
export declare class DeviceVideoSourceConfig extends Message<DeviceVideoSourceConfig> {
  /**
   * Device to capture from; the platform default device when unset.
   *
   * @generated from oneof livekit.proto.DeviceVideoSourceConfig.device
   */
  device: {
    /**
     * Position in the platform enumeration order.
     *
     * @generated from field: uint32 device_index = 1;
     */
    value: number;
    case: "deviceIndex";
  } | {
    /**
     * Platform-stable identifier, as reported by CaptureDeviceInfo.id.
     *
     * @generated from field: string device_id = 2;
     */
    value: string;
    case: "deviceId";
  } | { case: undefined; value?: undefined };

  /**
   * Format requested from the device; the device default when unset.
   *
   * @generated from field: optional livekit.proto.DeviceFormatRequest format = 3;
   */
  format?: DeviceFormatRequest;

  constructor(data?: PartialMessage<DeviceVideoSourceConfig>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DeviceVideoSourceConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeviceVideoSourceConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeviceVideoSourceConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeviceVideoSourceConfig;

  static equals(a: DeviceVideoSourceConfig | PlainMessage<DeviceVideoSourceConfig> | undefined, b: DeviceVideoSourceConfig | PlainMessage<DeviceVideoSourceConfig> | undefined): boolean;
}

/**
 * Video capture device discovered by ListCaptureDevicesRequest.
 *
 * @generated from message livekit.proto.CaptureDeviceInfo
 */
export declare class CaptureDeviceInfo extends Message<CaptureDeviceInfo> {
  /**
   * Platform-stable device identifier.
   *
   * @generated from field: required string id = 1;
   */
  id?: string;

  /**
   * Human-readable device name.
   *
   * @generated from field: required string name = 2;
   */
  name?: string;

  /**
   * Device model identifier, when available.
   *
   * @generated from field: optional string model_id = 3;
   */
  modelId?: string;

  /**
   * Device manufacturer, when available.
   *
   * @generated from field: optional string manufacturer = 4;
   */
  manufacturer?: string;

  /**
   * Capture formats reported by the device.
   *
   * @generated from field: repeated livekit.proto.DeviceFormat formats = 5;
   */
  formats: DeviceFormat[];

  /**
   * Whether `formats` is a complete list; some platforms do not enumerate
   * formats up front.
   *
   * @generated from field: required bool formats_complete = 6;
   */
  formatsComplete?: boolean;

  constructor(data?: PartialMessage<CaptureDeviceInfo>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureDeviceInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureDeviceInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureDeviceInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureDeviceInfo;

  static equals(a: CaptureDeviceInfo | PlainMessage<CaptureDeviceInfo> | undefined, b: CaptureDeviceInfo | PlainMessage<CaptureDeviceInfo> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.CaptureDeviceList
 */
export declare class CaptureDeviceList extends Message<CaptureDeviceList> {
  /**
   * @generated from field: repeated livekit.proto.CaptureDeviceInfo devices = 1;
   */
  devices: CaptureDeviceInfo[];

  constructor(data?: PartialMessage<CaptureDeviceList>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureDeviceList";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureDeviceList;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureDeviceList;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureDeviceList;

  static equals(a: CaptureDeviceList | PlainMessage<CaptureDeviceList> | undefined, b: CaptureDeviceList | PlainMessage<CaptureDeviceList> | undefined): boolean;
}

/**
 * List the video capture devices available on this machine.
 *
 * Completes asynchronously with a ListCaptureDevicesCallback: enumeration
 * queries the platform capture stack and may block briefly.
 *
 * @generated from message livekit.proto.ListCaptureDevicesRequest
 */
export declare class ListCaptureDevicesRequest extends Message<ListCaptureDevicesRequest> {
  /**
   * @generated from field: optional uint64 request_async_id = 1;
   */
  requestAsyncId?: bigint;

  constructor(data?: PartialMessage<ListCaptureDevicesRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.ListCaptureDevicesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCaptureDevicesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCaptureDevicesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCaptureDevicesRequest;

  static equals(a: ListCaptureDevicesRequest | PlainMessage<ListCaptureDevicesRequest> | undefined, b: ListCaptureDevicesRequest | PlainMessage<ListCaptureDevicesRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.ListCaptureDevicesResponse
 */
export declare class ListCaptureDevicesResponse extends Message<ListCaptureDevicesResponse> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  constructor(data?: PartialMessage<ListCaptureDevicesResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.ListCaptureDevicesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCaptureDevicesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCaptureDevicesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCaptureDevicesResponse;

  static equals(a: ListCaptureDevicesResponse | PlainMessage<ListCaptureDevicesResponse> | undefined, b: ListCaptureDevicesResponse | PlainMessage<ListCaptureDevicesResponse> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.ListCaptureDevicesCallback
 */
export declare class ListCaptureDevicesCallback extends Message<ListCaptureDevicesCallback> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  /**
   * @generated from oneof livekit.proto.ListCaptureDevicesCallback.message
   */
  message: {
    /**
     * @generated from field: string error = 2;
     */
    value: string;
    case: "error";
  } | {
    /**
     * @generated from field: livekit.proto.CaptureDeviceList devices = 3;
     */
    value: CaptureDeviceList;
    case: "devices";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<ListCaptureDevicesCallback>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.ListCaptureDevicesCallback";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListCaptureDevicesCallback;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListCaptureDevicesCallback;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListCaptureDevicesCallback;

  static equals(a: ListCaptureDevicesCallback | PlainMessage<ListCaptureDevicesCallback> | undefined, b: ListCaptureDevicesCallback | PlainMessage<ListCaptureDevicesCallback> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.CaptureSourceInfo
 */
export declare class CaptureSourceInfo extends Message<CaptureSourceInfo> {
  /**
   * @generated from field: required livekit.proto.CaptureSourceKind kind = 1;
   */
  kind?: CaptureSourceKind;

  /**
   * Declared or discovered stream resolution.
   *
   * @generated from field: required livekit.proto.VideoSourceResolution resolution = 2;
   */
  resolution?: VideoSourceResolution;

  /**
   * Codec produced by the source; encoded sources only.
   *
   * @generated from field: optional livekit.proto.VideoCodec codec = 3;
   */
  codec?: VideoCodec;

  /**
   * Publish options derived from the source (codec, encoder backend, ...).
   * Merge application options (e.g. track source) over these when calling
   * PublishTrackRequest.
   *
   * @generated from field: required livekit.proto.TrackPublishOptions recommended_publish_options = 4;
   */
  recommendedPublishOptions?: TrackPublishOptions;

  /**
   * RTC video source fed by this capture source; pass its handle to
   * CreateVideoTrackRequest. Owned by the client like any other handle.
   *
   * @generated from field: required livekit.proto.OwnedVideoSource video_source = 5;
   */
  videoSource?: OwnedVideoSource;

  constructor(data?: PartialMessage<CaptureSourceInfo>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureSourceInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureSourceInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureSourceInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureSourceInfo;

  static equals(a: CaptureSourceInfo | PlainMessage<CaptureSourceInfo> | undefined, b: CaptureSourceInfo | PlainMessage<CaptureSourceInfo> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.OwnedCaptureSource
 */
export declare class OwnedCaptureSource extends Message<OwnedCaptureSource> {
  /**
   * @generated from field: required livekit.proto.FfiOwnedHandle handle = 1;
   */
  handle?: FfiOwnedHandle;

  /**
   * @generated from field: required livekit.proto.CaptureSourceInfo info = 2;
   */
  info?: CaptureSourceInfo;

  constructor(data?: PartialMessage<OwnedCaptureSource>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.OwnedCaptureSource";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnedCaptureSource;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnedCaptureSource;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnedCaptureSource;

  static equals(a: OwnedCaptureSource | PlainMessage<OwnedCaptureSource> | undefined, b: OwnedCaptureSource | PlainMessage<OwnedCaptureSource> | undefined): boolean;
}

/**
 * Create a new capture source from configuration.
 *
 * Completes asynchronously with a NewCaptureSourceCallback: construction
 * starts the producer and may wait for its first output to discover stream
 * settings.
 *
 * @generated from message livekit.proto.NewCaptureSourceRequest
 */
export declare class NewCaptureSourceRequest extends Message<NewCaptureSourceRequest> {
  /**
   * @generated from oneof livekit.proto.NewCaptureSourceRequest.config
   */
  config: {
    /**
     * @generated from field: livekit.proto.GstreamerVideoSourceConfig gstreamer = 1;
     */
    value: GstreamerVideoSourceConfig;
    case: "gstreamer";
  } | {
    /**
     * @generated from field: livekit.proto.PatternVideoSourceConfig pattern = 2;
     */
    value: PatternVideoSourceConfig;
    case: "pattern";
  } | {
    /**
     * @generated from field: livekit.proto.DeviceVideoSourceConfig device = 4;
     */
    value: DeviceVideoSourceConfig;
    case: "device";
  } | {
    /**
     * @generated from field: livekit.proto.ClockVideoSourceConfig clock = 5;
     */
    value: ClockVideoSourceConfig;
    case: "clock";
  } | {
    /**
     * @generated from field: livekit.proto.RtspVideoSourceConfig rtsp = 6;
     */
    value: RtspVideoSourceConfig;
    case: "rtsp";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: optional uint64 request_async_id = 3;
   */
  requestAsyncId?: bigint;

  constructor(data?: PartialMessage<NewCaptureSourceRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.NewCaptureSourceRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NewCaptureSourceRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NewCaptureSourceRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NewCaptureSourceRequest;

  static equals(a: NewCaptureSourceRequest | PlainMessage<NewCaptureSourceRequest> | undefined, b: NewCaptureSourceRequest | PlainMessage<NewCaptureSourceRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.NewCaptureSourceResponse
 */
export declare class NewCaptureSourceResponse extends Message<NewCaptureSourceResponse> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  constructor(data?: PartialMessage<NewCaptureSourceResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.NewCaptureSourceResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NewCaptureSourceResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NewCaptureSourceResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NewCaptureSourceResponse;

  static equals(a: NewCaptureSourceResponse | PlainMessage<NewCaptureSourceResponse> | undefined, b: NewCaptureSourceResponse | PlainMessage<NewCaptureSourceResponse> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.NewCaptureSourceCallback
 */
export declare class NewCaptureSourceCallback extends Message<NewCaptureSourceCallback> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  /**
   * @generated from oneof livekit.proto.NewCaptureSourceCallback.message
   */
  message: {
    /**
     * @generated from field: string error = 2;
     */
    value: string;
    case: "error";
  } | {
    /**
     * @generated from field: livekit.proto.OwnedCaptureSource source = 3;
     */
    value: OwnedCaptureSource;
    case: "source";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<NewCaptureSourceCallback>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.NewCaptureSourceCallback";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NewCaptureSourceCallback;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NewCaptureSourceCallback;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NewCaptureSourceCallback;

  static equals(a: NewCaptureSourceCallback | PlainMessage<NewCaptureSourceCallback> | undefined, b: NewCaptureSourceCallback | PlainMessage<NewCaptureSourceCallback> | undefined): boolean;
}

/**
 * Start pumping frames from a capture source into its RTC video source.
 *
 * @generated from message livekit.proto.StartCaptureRequest
 */
export declare class StartCaptureRequest extends Message<StartCaptureRequest> {
  /**
   * @generated from field: required uint64 capture_handle = 1;
   */
  captureHandle?: bigint;

  constructor(data?: PartialMessage<StartCaptureRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StartCaptureRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartCaptureRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartCaptureRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartCaptureRequest;

  static equals(a: StartCaptureRequest | PlainMessage<StartCaptureRequest> | undefined, b: StartCaptureRequest | PlainMessage<StartCaptureRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.StartCaptureResponse
 */
export declare class StartCaptureResponse extends Message<StartCaptureResponse> {
  /**
   * @generated from field: optional string error = 1;
   */
  error?: string;

  constructor(data?: PartialMessage<StartCaptureResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StartCaptureResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StartCaptureResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StartCaptureResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StartCaptureResponse;

  static equals(a: StartCaptureResponse | PlainMessage<StartCaptureResponse> | undefined, b: StartCaptureResponse | PlainMessage<StartCaptureResponse> | undefined): boolean;
}

/**
 * Signal a running capture to stop after the frame in flight. The terminal
 * CaptureSourceEvent follows shortly. Stopping an already-finished capture
 * is a no-op.
 *
 * @generated from message livekit.proto.StopCaptureRequest
 */
export declare class StopCaptureRequest extends Message<StopCaptureRequest> {
  /**
   * @generated from field: required uint64 capture_handle = 1;
   */
  captureHandle?: bigint;

  constructor(data?: PartialMessage<StopCaptureRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StopCaptureRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopCaptureRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopCaptureRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopCaptureRequest;

  static equals(a: StopCaptureRequest | PlainMessage<StopCaptureRequest> | undefined, b: StopCaptureRequest | PlainMessage<StopCaptureRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.StopCaptureResponse
 */
export declare class StopCaptureResponse extends Message<StopCaptureResponse> {
  /**
   * @generated from field: optional string error = 1;
   */
  error?: string;

  constructor(data?: PartialMessage<StopCaptureResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.StopCaptureResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopCaptureResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopCaptureResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopCaptureResponse;

  static equals(a: StopCaptureResponse | PlainMessage<StopCaptureResponse> | undefined, b: StopCaptureResponse | PlainMessage<StopCaptureResponse> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.CaptureFinished
 */
export declare class CaptureFinished extends Message<CaptureFinished> {
  /**
   * @generated from field: required uint64 frames_captured = 1;
   */
  framesCaptured?: bigint;

  /**
   * @generated from field: required livekit.proto.CaptureExit exit = 2;
   */
  exit?: CaptureExit;

  constructor(data?: PartialMessage<CaptureFinished>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureFinished";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureFinished;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureFinished;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureFinished;

  static equals(a: CaptureFinished | PlainMessage<CaptureFinished> | undefined, b: CaptureFinished | PlainMessage<CaptureFinished> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.CaptureError
 */
export declare class CaptureError extends Message<CaptureError> {
  /**
   * @generated from field: required string error = 1;
   */
  error?: string;

  constructor(data?: PartialMessage<CaptureError>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureError;

  static equals(a: CaptureError | PlainMessage<CaptureError> | undefined, b: CaptureError | PlainMessage<CaptureError> | undefined): boolean;
}

/**
 * Delivered exactly once when a started capture ends, regardless of why
 * (stop request, end of stream, or failure).
 *
 * @generated from message livekit.proto.CaptureSourceEvent
 */
export declare class CaptureSourceEvent extends Message<CaptureSourceEvent> {
  /**
   * @generated from field: required uint64 capture_handle = 1;
   */
  captureHandle?: bigint;

  /**
   * @generated from oneof livekit.proto.CaptureSourceEvent.message
   */
  message: {
    /**
     * @generated from field: livekit.proto.CaptureFinished finished = 2;
     */
    value: CaptureFinished;
    case: "finished";
  } | {
    /**
     * @generated from field: livekit.proto.CaptureError error = 3;
     */
    value: CaptureError;
    case: "error";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<CaptureSourceEvent>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.CaptureSourceEvent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptureSourceEvent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptureSourceEvent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptureSourceEvent;

  static equals(a: CaptureSourceEvent | PlainMessage<CaptureSourceEvent> | undefined, b: CaptureSourceEvent | PlainMessage<CaptureSourceEvent> | undefined): boolean;
}

