// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file data_track.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto2 } from "@bufbuild/protobuf";
import type { FfiOwnedHandle } from "./handle_pb.js";

/**
 * @generated from enum livekit.proto.DataTrackErrorCode
 */
export declare enum DataTrackErrorCode {
  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_INVALID_HANDLE = 1;
   */
  INVALID_HANDLE = 1,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_DUPLICATE_TRACK_NAME = 2;
   */
  DUPLICATE_TRACK_NAME = 2,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_TRACK_UNPUBLISHED = 3;
   */
  TRACK_UNPUBLISHED = 3,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_BUFFER_FULL = 4;
   */
  BUFFER_FULL = 4,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_SUBSCRIPTION_CLOSED = 5;
   */
  SUBSCRIPTION_CLOSED = 5,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_CANCELLED = 6;
   */
  CANCELLED = 6,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_PROTOCOL_ERROR = 7;
   */
  PROTOCOL_ERROR = 7,

  /**
   * @generated from enum value: DATA_TRACK_ERROR_CODE_INTERNAL = 8;
   */
  INTERNAL = 8,
}

/**
 * @generated from enum livekit.proto.PublishDataTrackErrorCode
 */
export declare enum PublishDataTrackErrorCode {
  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_INVALID_HANDLE = 1;
   */
  INVALID_HANDLE = 1,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_DUPLICATE_NAME = 2;
   */
  DUPLICATE_NAME = 2,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_TIMEOUT = 3;
   */
  TIMEOUT = 3,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_DISCONNECTED = 4;
   */
  DISCONNECTED = 4,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_NOT_ALLOWED = 5;
   */
  NOT_ALLOWED = 5,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_INVALID_NAME = 6;
   */
  INVALID_NAME = 6,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_LIMIT_REACHED = 7;
   */
  LIMIT_REACHED = 7,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_PROTOCOL_ERROR = 8;
   */
  PROTOCOL_ERROR = 8,

  /**
   * @generated from enum value: PUBLISH_DATA_TRACK_ERROR_CODE_INTERNAL = 9;
   */
  INTERNAL = 9,
}

/**
 * @generated from enum livekit.proto.LocalDataTrackTryPushErrorCode
 */
export declare enum LocalDataTrackTryPushErrorCode {
  /**
   * @generated from enum value: LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_INVALID_HANDLE = 1;
   */
  INVALID_HANDLE = 1,

  /**
   * @generated from enum value: LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_TRACK_UNPUBLISHED = 2;
   */
  TRACK_UNPUBLISHED = 2,

  /**
   * @generated from enum value: LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_QUEUE_FULL = 3;
   */
  QUEUE_FULL = 3,

  /**
   * @generated from enum value: LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_INTERNAL = 4;
   */
  INTERNAL = 4,
}

/**
 * @generated from enum livekit.proto.SubscribeDataTrackErrorCode
 */
export declare enum SubscribeDataTrackErrorCode {
  /**
   * @generated from enum value: SUBSCRIBE_DATA_TRACK_ERROR_CODE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: SUBSCRIBE_DATA_TRACK_ERROR_CODE_INVALID_HANDLE = 1;
   */
  INVALID_HANDLE = 1,

  /**
   * @generated from enum value: SUBSCRIBE_DATA_TRACK_ERROR_CODE_UNPUBLISHED = 2;
   */
  UNPUBLISHED = 2,

  /**
   * @generated from enum value: SUBSCRIBE_DATA_TRACK_ERROR_CODE_TIMEOUT = 3;
   */
  TIMEOUT = 3,

  /**
   * @generated from enum value: SUBSCRIBE_DATA_TRACK_ERROR_CODE_DISCONNECTED = 4;
   */
  DISCONNECTED = 4,

  /**
   * @generated from enum value: SUBSCRIBE_DATA_TRACK_ERROR_CODE_PROTOCOL_ERROR = 5;
   */
  PROTOCOL_ERROR = 5,

  /**
   * @generated from enum value: SUBSCRIBE_DATA_TRACK_ERROR_CODE_INTERNAL = 6;
   */
  INTERNAL = 6,
}

/**
 * Information about a published data track.
 *
 * @generated from message livekit.proto.DataTrackInfo
 */
export declare class DataTrackInfo extends Message<DataTrackInfo> {
  /**
   * Name of the track assigned by the publisher.
   *
   * @generated from field: required string name = 1;
   */
  name?: string;

  /**
   * SFU-assigned track identifier.
   *
   * @generated from field: required string sid = 2;
   */
  sid?: string;

  /**
   * Whether or not frames sent on the track use end-to-end encryption.
   *
   * @generated from field: required bool uses_e2ee = 3;
   */
  usesE2ee?: boolean;

  constructor(data?: PartialMessage<DataTrackInfo>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackInfo;

  static equals(a: DataTrackInfo | PlainMessage<DataTrackInfo> | undefined, b: DataTrackInfo | PlainMessage<DataTrackInfo> | undefined): boolean;
}

/**
 * A frame published on a data track.
 *
 * @generated from message livekit.proto.DataTrackFrame
 */
export declare class DataTrackFrame extends Message<DataTrackFrame> {
  /**
   * @generated from field: required bytes payload = 1;
   */
  payload?: Uint8Array;

  /**
   * @generated from field: optional uint64 user_timestamp = 2;
   */
  userTimestamp?: bigint;

  constructor(data?: PartialMessage<DataTrackFrame>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackFrame";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackFrame;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackFrame;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackFrame;

  static equals(a: DataTrackFrame | PlainMessage<DataTrackFrame> | undefined, b: DataTrackFrame | PlainMessage<DataTrackFrame> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.DataTrackError
 */
export declare class DataTrackError extends Message<DataTrackError> {
  /**
   * @generated from field: required livekit.proto.DataTrackErrorCode code = 1;
   */
  code?: DataTrackErrorCode;

  /**
   * @generated from field: required string message = 2;
   */
  message?: string;

  constructor(data?: PartialMessage<DataTrackError>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackError;

  static equals(a: DataTrackError | PlainMessage<DataTrackError> | undefined, b: DataTrackError | PlainMessage<DataTrackError> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.PublishDataTrackError
 */
export declare class PublishDataTrackError extends Message<PublishDataTrackError> {
  /**
   * @generated from field: required livekit.proto.PublishDataTrackErrorCode code = 1;
   */
  code?: PublishDataTrackErrorCode;

  /**
   * @generated from field: required string message = 2;
   */
  message?: string;

  constructor(data?: PartialMessage<PublishDataTrackError>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.PublishDataTrackError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishDataTrackError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishDataTrackError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishDataTrackError;

  static equals(a: PublishDataTrackError | PlainMessage<PublishDataTrackError> | undefined, b: PublishDataTrackError | PlainMessage<PublishDataTrackError> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.LocalDataTrackTryPushError
 */
export declare class LocalDataTrackTryPushError extends Message<LocalDataTrackTryPushError> {
  /**
   * @generated from field: required livekit.proto.LocalDataTrackTryPushErrorCode code = 1;
   */
  code?: LocalDataTrackTryPushErrorCode;

  /**
   * @generated from field: required string message = 2;
   */
  message?: string;

  constructor(data?: PartialMessage<LocalDataTrackTryPushError>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.LocalDataTrackTryPushError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalDataTrackTryPushError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalDataTrackTryPushError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalDataTrackTryPushError;

  static equals(a: LocalDataTrackTryPushError | PlainMessage<LocalDataTrackTryPushError> | undefined, b: LocalDataTrackTryPushError | PlainMessage<LocalDataTrackTryPushError> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.SubscribeDataTrackError
 */
export declare class SubscribeDataTrackError extends Message<SubscribeDataTrackError> {
  /**
   * @generated from field: required livekit.proto.SubscribeDataTrackErrorCode code = 1;
   */
  code?: SubscribeDataTrackErrorCode;

  /**
   * @generated from field: required string message = 2;
   */
  message?: string;

  constructor(data?: PartialMessage<SubscribeDataTrackError>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.SubscribeDataTrackError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeDataTrackError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeDataTrackError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeDataTrackError;

  static equals(a: SubscribeDataTrackError | PlainMessage<SubscribeDataTrackError> | undefined, b: SubscribeDataTrackError | PlainMessage<SubscribeDataTrackError> | undefined): boolean;
}

/**
 * Options for publishing a data track.
 *
 * @generated from message livekit.proto.DataTrackOptions
 */
export declare class DataTrackOptions extends Message<DataTrackOptions> {
  /**
   * Track name used to identify the track to other participants.
   *
   * Must not be empty and must be unique per publisher.
   *
   *
   * @generated from field: required string name = 1;
   */
  name?: string;

  constructor(data?: PartialMessage<DataTrackOptions>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackOptions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackOptions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackOptions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackOptions;

  static equals(a: DataTrackOptions | PlainMessage<DataTrackOptions> | undefined, b: DataTrackOptions | PlainMessage<DataTrackOptions> | undefined): boolean;
}

/**
 * Publish a data track
 *
 * @generated from message livekit.proto.PublishDataTrackRequest
 */
export declare class PublishDataTrackRequest extends Message<PublishDataTrackRequest> {
  /**
   * @generated from field: required uint64 local_participant_handle = 1;
   */
  localParticipantHandle?: bigint;

  /**
   * @generated from field: required livekit.proto.DataTrackOptions options = 2;
   */
  options?: DataTrackOptions;

  /**
   * @generated from field: optional uint64 request_async_id = 3;
   */
  requestAsyncId?: bigint;

  constructor(data?: PartialMessage<PublishDataTrackRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.PublishDataTrackRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishDataTrackRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishDataTrackRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishDataTrackRequest;

  static equals(a: PublishDataTrackRequest | PlainMessage<PublishDataTrackRequest> | undefined, b: PublishDataTrackRequest | PlainMessage<PublishDataTrackRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.PublishDataTrackResponse
 */
export declare class PublishDataTrackResponse extends Message<PublishDataTrackResponse> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  constructor(data?: PartialMessage<PublishDataTrackResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.PublishDataTrackResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishDataTrackResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishDataTrackResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishDataTrackResponse;

  static equals(a: PublishDataTrackResponse | PlainMessage<PublishDataTrackResponse> | undefined, b: PublishDataTrackResponse | PlainMessage<PublishDataTrackResponse> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.PublishDataTrackCallback
 */
export declare class PublishDataTrackCallback extends Message<PublishDataTrackCallback> {
  /**
   * @generated from field: required uint64 async_id = 1;
   */
  asyncId?: bigint;

  /**
   * @generated from oneof livekit.proto.PublishDataTrackCallback.result
   */
  result: {
    /**
     * @generated from field: livekit.proto.OwnedLocalDataTrack track = 2;
     */
    value: OwnedLocalDataTrack;
    case: "track";
  } | {
    /**
     * @generated from field: livekit.proto.PublishDataTrackError error = 3;
     */
    value: PublishDataTrackError;
    case: "error";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<PublishDataTrackCallback>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.PublishDataTrackCallback";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishDataTrackCallback;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishDataTrackCallback;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishDataTrackCallback;

  static equals(a: PublishDataTrackCallback | PlainMessage<PublishDataTrackCallback> | undefined, b: PublishDataTrackCallback | PlainMessage<PublishDataTrackCallback> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.OwnedLocalDataTrack
 */
export declare class OwnedLocalDataTrack extends Message<OwnedLocalDataTrack> {
  /**
   * @generated from field: required livekit.proto.FfiOwnedHandle handle = 1;
   */
  handle?: FfiOwnedHandle;

  /**
   * @generated from field: required livekit.proto.DataTrackInfo info = 2;
   */
  info?: DataTrackInfo;

  constructor(data?: PartialMessage<OwnedLocalDataTrack>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.OwnedLocalDataTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnedLocalDataTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnedLocalDataTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnedLocalDataTrack;

  static equals(a: OwnedLocalDataTrack | PlainMessage<OwnedLocalDataTrack> | undefined, b: OwnedLocalDataTrack | PlainMessage<OwnedLocalDataTrack> | undefined): boolean;
}

/**
 * Try pushing a frame to subscribers of the track.
 *
 * @generated from message livekit.proto.LocalDataTrackTryPushRequest
 */
export declare class LocalDataTrackTryPushRequest extends Message<LocalDataTrackTryPushRequest> {
  /**
   * @generated from field: required uint64 track_handle = 1;
   */
  trackHandle?: bigint;

  /**
   * @generated from field: required livekit.proto.DataTrackFrame frame = 2;
   */
  frame?: DataTrackFrame;

  constructor(data?: PartialMessage<LocalDataTrackTryPushRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.LocalDataTrackTryPushRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalDataTrackTryPushRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalDataTrackTryPushRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalDataTrackTryPushRequest;

  static equals(a: LocalDataTrackTryPushRequest | PlainMessage<LocalDataTrackTryPushRequest> | undefined, b: LocalDataTrackTryPushRequest | PlainMessage<LocalDataTrackTryPushRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.LocalDataTrackTryPushResponse
 */
export declare class LocalDataTrackTryPushResponse extends Message<LocalDataTrackTryPushResponse> {
  /**
   * @generated from field: optional livekit.proto.LocalDataTrackTryPushError error = 2;
   */
  error?: LocalDataTrackTryPushError;

  constructor(data?: PartialMessage<LocalDataTrackTryPushResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.LocalDataTrackTryPushResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalDataTrackTryPushResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalDataTrackTryPushResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalDataTrackTryPushResponse;

  static equals(a: LocalDataTrackTryPushResponse | PlainMessage<LocalDataTrackTryPushResponse> | undefined, b: LocalDataTrackTryPushResponse | PlainMessage<LocalDataTrackTryPushResponse> | undefined): boolean;
}

/**
 * Checks if the track is still published.
 *
 * @generated from message livekit.proto.LocalDataTrackIsPublishedRequest
 */
export declare class LocalDataTrackIsPublishedRequest extends Message<LocalDataTrackIsPublishedRequest> {
  /**
   * @generated from field: required uint64 track_handle = 1;
   */
  trackHandle?: bigint;

  constructor(data?: PartialMessage<LocalDataTrackIsPublishedRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.LocalDataTrackIsPublishedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalDataTrackIsPublishedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalDataTrackIsPublishedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalDataTrackIsPublishedRequest;

  static equals(a: LocalDataTrackIsPublishedRequest | PlainMessage<LocalDataTrackIsPublishedRequest> | undefined, b: LocalDataTrackIsPublishedRequest | PlainMessage<LocalDataTrackIsPublishedRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.LocalDataTrackIsPublishedResponse
 */
export declare class LocalDataTrackIsPublishedResponse extends Message<LocalDataTrackIsPublishedResponse> {
  /**
   * @generated from field: required bool is_published = 1;
   */
  isPublished?: boolean;

  constructor(data?: PartialMessage<LocalDataTrackIsPublishedResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.LocalDataTrackIsPublishedResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalDataTrackIsPublishedResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalDataTrackIsPublishedResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalDataTrackIsPublishedResponse;

  static equals(a: LocalDataTrackIsPublishedResponse | PlainMessage<LocalDataTrackIsPublishedResponse> | undefined, b: LocalDataTrackIsPublishedResponse | PlainMessage<LocalDataTrackIsPublishedResponse> | undefined): boolean;
}

/**
 * Unpublishes the track.
 *
 * @generated from message livekit.proto.LocalDataTrackUnpublishRequest
 */
export declare class LocalDataTrackUnpublishRequest extends Message<LocalDataTrackUnpublishRequest> {
  /**
   * @generated from field: required uint64 track_handle = 1;
   */
  trackHandle?: bigint;

  constructor(data?: PartialMessage<LocalDataTrackUnpublishRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.LocalDataTrackUnpublishRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalDataTrackUnpublishRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalDataTrackUnpublishRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalDataTrackUnpublishRequest;

  static equals(a: LocalDataTrackUnpublishRequest | PlainMessage<LocalDataTrackUnpublishRequest> | undefined, b: LocalDataTrackUnpublishRequest | PlainMessage<LocalDataTrackUnpublishRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.LocalDataTrackUnpublishResponse
 */
export declare class LocalDataTrackUnpublishResponse extends Message<LocalDataTrackUnpublishResponse> {
  constructor(data?: PartialMessage<LocalDataTrackUnpublishResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.LocalDataTrackUnpublishResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LocalDataTrackUnpublishResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LocalDataTrackUnpublishResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LocalDataTrackUnpublishResponse;

  static equals(a: LocalDataTrackUnpublishResponse | PlainMessage<LocalDataTrackUnpublishResponse> | undefined, b: LocalDataTrackUnpublishResponse | PlainMessage<LocalDataTrackUnpublishResponse> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.OwnedRemoteDataTrack
 */
export declare class OwnedRemoteDataTrack extends Message<OwnedRemoteDataTrack> {
  /**
   * @generated from field: required livekit.proto.FfiOwnedHandle handle = 1;
   */
  handle?: FfiOwnedHandle;

  /**
   * @generated from field: required livekit.proto.DataTrackInfo info = 2;
   */
  info?: DataTrackInfo;

  /**
   * Identity of the remote participant who published the track.
   *
   * @generated from field: required string publisher_identity = 3;
   */
  publisherIdentity?: string;

  constructor(data?: PartialMessage<OwnedRemoteDataTrack>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.OwnedRemoteDataTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnedRemoteDataTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnedRemoteDataTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnedRemoteDataTrack;

  static equals(a: OwnedRemoteDataTrack | PlainMessage<OwnedRemoteDataTrack> | undefined, b: OwnedRemoteDataTrack | PlainMessage<OwnedRemoteDataTrack> | undefined): boolean;
}

/**
 * Handle to an active data track subscription.
 *
 * Dropping the handle will unsubscribe from the track.
 *
 *
 * @generated from message livekit.proto.OwnedDataTrackStream
 */
export declare class OwnedDataTrackStream extends Message<OwnedDataTrackStream> {
  /**
   * @generated from field: required livekit.proto.FfiOwnedHandle handle = 1;
   */
  handle?: FfiOwnedHandle;

  constructor(data?: PartialMessage<OwnedDataTrackStream>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.OwnedDataTrackStream";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnedDataTrackStream;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnedDataTrackStream;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnedDataTrackStream;

  static equals(a: OwnedDataTrackStream | PlainMessage<OwnedDataTrackStream> | undefined, b: OwnedDataTrackStream | PlainMessage<OwnedDataTrackStream> | undefined): boolean;
}

/**
 * Reserved for future subscription options.
 *
 * @generated from message livekit.proto.DataTrackSubscribeOptions
 */
export declare class DataTrackSubscribeOptions extends Message<DataTrackSubscribeOptions> {
  /**
   * Maximum number of frames to buffer internally.
   *
   * @generated from field: optional uint32 buffer_size = 1;
   */
  bufferSize?: number;

  constructor(data?: PartialMessage<DataTrackSubscribeOptions>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackSubscribeOptions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackSubscribeOptions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackSubscribeOptions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackSubscribeOptions;

  static equals(a: DataTrackSubscribeOptions | PlainMessage<DataTrackSubscribeOptions> | undefined, b: DataTrackSubscribeOptions | PlainMessage<DataTrackSubscribeOptions> | undefined): boolean;
}

/**
 * Checks if the track is still published.
 *
 * @generated from message livekit.proto.RemoteDataTrackIsPublishedRequest
 */
export declare class RemoteDataTrackIsPublishedRequest extends Message<RemoteDataTrackIsPublishedRequest> {
  /**
   * @generated from field: required uint64 track_handle = 1;
   */
  trackHandle?: bigint;

  constructor(data?: PartialMessage<RemoteDataTrackIsPublishedRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.RemoteDataTrackIsPublishedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoteDataTrackIsPublishedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoteDataTrackIsPublishedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoteDataTrackIsPublishedRequest;

  static equals(a: RemoteDataTrackIsPublishedRequest | PlainMessage<RemoteDataTrackIsPublishedRequest> | undefined, b: RemoteDataTrackIsPublishedRequest | PlainMessage<RemoteDataTrackIsPublishedRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.RemoteDataTrackIsPublishedResponse
 */
export declare class RemoteDataTrackIsPublishedResponse extends Message<RemoteDataTrackIsPublishedResponse> {
  /**
   * @generated from field: required bool is_published = 1;
   */
  isPublished?: boolean;

  constructor(data?: PartialMessage<RemoteDataTrackIsPublishedResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.RemoteDataTrackIsPublishedResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoteDataTrackIsPublishedResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoteDataTrackIsPublishedResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoteDataTrackIsPublishedResponse;

  static equals(a: RemoteDataTrackIsPublishedResponse | PlainMessage<RemoteDataTrackIsPublishedResponse> | undefined, b: RemoteDataTrackIsPublishedResponse | PlainMessage<RemoteDataTrackIsPublishedResponse> | undefined): boolean;
}

/**
 * Subscribe to a data track.
 *
 * @generated from message livekit.proto.SubscribeDataTrackRequest
 */
export declare class SubscribeDataTrackRequest extends Message<SubscribeDataTrackRequest> {
  /**
   * @generated from field: required uint64 track_handle = 1;
   */
  trackHandle?: bigint;

  /**
   * @generated from field: required livekit.proto.DataTrackSubscribeOptions options = 2;
   */
  options?: DataTrackSubscribeOptions;

  constructor(data?: PartialMessage<SubscribeDataTrackRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.SubscribeDataTrackRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeDataTrackRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeDataTrackRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeDataTrackRequest;

  static equals(a: SubscribeDataTrackRequest | PlainMessage<SubscribeDataTrackRequest> | undefined, b: SubscribeDataTrackRequest | PlainMessage<SubscribeDataTrackRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.SubscribeDataTrackResponse
 */
export declare class SubscribeDataTrackResponse extends Message<SubscribeDataTrackResponse> {
  /**
   * @generated from field: required livekit.proto.OwnedDataTrackStream stream = 1;
   */
  stream?: OwnedDataTrackStream;

  constructor(data?: PartialMessage<SubscribeDataTrackResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.SubscribeDataTrackResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubscribeDataTrackResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubscribeDataTrackResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubscribeDataTrackResponse;

  static equals(a: SubscribeDataTrackResponse | PlainMessage<SubscribeDataTrackResponse> | undefined, b: SubscribeDataTrackResponse | PlainMessage<SubscribeDataTrackResponse> | undefined): boolean;
}

/**
 * Signal readiness to handle the next frame.
 *
 * This allows the client to put backpressure on the internal receive buffer.
 * Sending this request will cause the next frame to be sent via `DataTrackStreamFrameReceived`
 * once one is available.
 *
 *
 * @generated from message livekit.proto.DataTrackStreamReadRequest
 */
export declare class DataTrackStreamReadRequest extends Message<DataTrackStreamReadRequest> {
  /**
   * @generated from field: required uint64 stream_handle = 1;
   */
  streamHandle?: bigint;

  constructor(data?: PartialMessage<DataTrackStreamReadRequest>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackStreamReadRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackStreamReadRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackStreamReadRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackStreamReadRequest;

  static equals(a: DataTrackStreamReadRequest | PlainMessage<DataTrackStreamReadRequest> | undefined, b: DataTrackStreamReadRequest | PlainMessage<DataTrackStreamReadRequest> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.DataTrackStreamReadResponse
 */
export declare class DataTrackStreamReadResponse extends Message<DataTrackStreamReadResponse> {
  constructor(data?: PartialMessage<DataTrackStreamReadResponse>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackStreamReadResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackStreamReadResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackStreamReadResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackStreamReadResponse;

  static equals(a: DataTrackStreamReadResponse | PlainMessage<DataTrackStreamReadResponse> | undefined, b: DataTrackStreamReadResponse | PlainMessage<DataTrackStreamReadResponse> | undefined): boolean;
}

/**
 * Event emitted on an active stream.
 *
 * @generated from message livekit.proto.DataTrackStreamEvent
 */
export declare class DataTrackStreamEvent extends Message<DataTrackStreamEvent> {
  /**
   * @generated from field: required uint64 stream_handle = 1;
   */
  streamHandle?: bigint;

  /**
   * @generated from oneof livekit.proto.DataTrackStreamEvent.detail
   */
  detail: {
    /**
     * @generated from field: livekit.proto.DataTrackStreamFrameReceived frame_received = 2;
     */
    value: DataTrackStreamFrameReceived;
    case: "frameReceived";
  } | {
    /**
     * @generated from field: livekit.proto.DataTrackStreamEOS eos = 3;
     */
    value: DataTrackStreamEOS;
    case: "eos";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<DataTrackStreamEvent>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackStreamEvent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackStreamEvent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackStreamEvent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackStreamEvent;

  static equals(a: DataTrackStreamEvent | PlainMessage<DataTrackStreamEvent> | undefined, b: DataTrackStreamEvent | PlainMessage<DataTrackStreamEvent> | undefined): boolean;
}

/**
 * A frame was received.
 *
 * @generated from message livekit.proto.DataTrackStreamFrameReceived
 */
export declare class DataTrackStreamFrameReceived extends Message<DataTrackStreamFrameReceived> {
  /**
   * @generated from field: required livekit.proto.DataTrackFrame frame = 1;
   */
  frame?: DataTrackFrame;

  constructor(data?: PartialMessage<DataTrackStreamFrameReceived>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackStreamFrameReceived";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackStreamFrameReceived;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackStreamFrameReceived;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackStreamFrameReceived;

  static equals(a: DataTrackStreamFrameReceived | PlainMessage<DataTrackStreamFrameReceived> | undefined, b: DataTrackStreamFrameReceived | PlainMessage<DataTrackStreamFrameReceived> | undefined): boolean;
}

/**
 * Stream has ended.
 *
 * @generated from message livekit.proto.DataTrackStreamEOS
 */
export declare class DataTrackStreamEOS extends Message<DataTrackStreamEOS> {
  /**
   * If the track could not be subscribed to, a message describing the error.
   * Absent if the stream ended normally.
   *
   * @generated from field: optional string error = 1;
   */
  error?: string;

  constructor(data?: PartialMessage<DataTrackStreamEOS>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.DataTrackStreamEOS";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataTrackStreamEOS;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataTrackStreamEOS;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataTrackStreamEOS;

  static equals(a: DataTrackStreamEOS | PlainMessage<DataTrackStreamEOS> | undefined, b: DataTrackStreamEOS | PlainMessage<DataTrackStreamEOS> | undefined): boolean;
}

