// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file data_track.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { proto2 } = require("@bufbuild/protobuf");
const { FfiOwnedHandle } = require("./handle_pb.js");

/**
 * @generated from enum livekit.proto.DataTrackErrorCode
 */
const DataTrackErrorCode = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.DataTrackErrorCode",
  [
    {no: 0, name: "DATA_TRACK_ERROR_CODE_UNKNOWN", localName: "UNKNOWN"},
    {no: 1, name: "DATA_TRACK_ERROR_CODE_INVALID_HANDLE", localName: "INVALID_HANDLE"},
    {no: 2, name: "DATA_TRACK_ERROR_CODE_DUPLICATE_TRACK_NAME", localName: "DUPLICATE_TRACK_NAME"},
    {no: 3, name: "DATA_TRACK_ERROR_CODE_TRACK_UNPUBLISHED", localName: "TRACK_UNPUBLISHED"},
    {no: 4, name: "DATA_TRACK_ERROR_CODE_BUFFER_FULL", localName: "BUFFER_FULL"},
    {no: 5, name: "DATA_TRACK_ERROR_CODE_SUBSCRIPTION_CLOSED", localName: "SUBSCRIPTION_CLOSED"},
    {no: 6, name: "DATA_TRACK_ERROR_CODE_CANCELLED", localName: "CANCELLED"},
    {no: 7, name: "DATA_TRACK_ERROR_CODE_PROTOCOL_ERROR", localName: "PROTOCOL_ERROR"},
    {no: 8, name: "DATA_TRACK_ERROR_CODE_INTERNAL", localName: "INTERNAL"},
  ],
);

/**
 * @generated from enum livekit.proto.PublishDataTrackErrorCode
 */
const PublishDataTrackErrorCode = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.PublishDataTrackErrorCode",
  [
    {no: 0, name: "PUBLISH_DATA_TRACK_ERROR_CODE_UNKNOWN", localName: "UNKNOWN"},
    {no: 1, name: "PUBLISH_DATA_TRACK_ERROR_CODE_INVALID_HANDLE", localName: "INVALID_HANDLE"},
    {no: 2, name: "PUBLISH_DATA_TRACK_ERROR_CODE_DUPLICATE_NAME", localName: "DUPLICATE_NAME"},
    {no: 3, name: "PUBLISH_DATA_TRACK_ERROR_CODE_TIMEOUT", localName: "TIMEOUT"},
    {no: 4, name: "PUBLISH_DATA_TRACK_ERROR_CODE_DISCONNECTED", localName: "DISCONNECTED"},
    {no: 5, name: "PUBLISH_DATA_TRACK_ERROR_CODE_NOT_ALLOWED", localName: "NOT_ALLOWED"},
    {no: 6, name: "PUBLISH_DATA_TRACK_ERROR_CODE_INVALID_NAME", localName: "INVALID_NAME"},
    {no: 7, name: "PUBLISH_DATA_TRACK_ERROR_CODE_LIMIT_REACHED", localName: "LIMIT_REACHED"},
    {no: 8, name: "PUBLISH_DATA_TRACK_ERROR_CODE_PROTOCOL_ERROR", localName: "PROTOCOL_ERROR"},
    {no: 9, name: "PUBLISH_DATA_TRACK_ERROR_CODE_INTERNAL", localName: "INTERNAL"},
  ],
);

/**
 * @generated from enum livekit.proto.LocalDataTrackTryPushErrorCode
 */
const LocalDataTrackTryPushErrorCode = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.LocalDataTrackTryPushErrorCode",
  [
    {no: 0, name: "LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_UNKNOWN", localName: "UNKNOWN"},
    {no: 1, name: "LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_INVALID_HANDLE", localName: "INVALID_HANDLE"},
    {no: 2, name: "LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_TRACK_UNPUBLISHED", localName: "TRACK_UNPUBLISHED"},
    {no: 3, name: "LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_QUEUE_FULL", localName: "QUEUE_FULL"},
    {no: 4, name: "LOCAL_DATA_TRACK_TRY_PUSH_ERROR_CODE_INTERNAL", localName: "INTERNAL"},
  ],
);

/**
 * @generated from enum livekit.proto.SubscribeDataTrackErrorCode
 */
const SubscribeDataTrackErrorCode = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.SubscribeDataTrackErrorCode",
  [
    {no: 0, name: "SUBSCRIBE_DATA_TRACK_ERROR_CODE_UNKNOWN", localName: "UNKNOWN"},
    {no: 1, name: "SUBSCRIBE_DATA_TRACK_ERROR_CODE_INVALID_HANDLE", localName: "INVALID_HANDLE"},
    {no: 2, name: "SUBSCRIBE_DATA_TRACK_ERROR_CODE_UNPUBLISHED", localName: "UNPUBLISHED"},
    {no: 3, name: "SUBSCRIBE_DATA_TRACK_ERROR_CODE_TIMEOUT", localName: "TIMEOUT"},
    {no: 4, name: "SUBSCRIBE_DATA_TRACK_ERROR_CODE_DISCONNECTED", localName: "DISCONNECTED"},
    {no: 5, name: "SUBSCRIBE_DATA_TRACK_ERROR_CODE_PROTOCOL_ERROR", localName: "PROTOCOL_ERROR"},
    {no: 6, name: "SUBSCRIBE_DATA_TRACK_ERROR_CODE_INTERNAL", localName: "INTERNAL"},
  ],
);

/**
 * Information about a published data track.
 *
 * @generated from message livekit.proto.DataTrackInfo
 */
const DataTrackInfo = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackInfo",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "uses_e2ee", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * A frame published on a data track.
 *
 * @generated from message livekit.proto.DataTrackFrame
 */
const DataTrackFrame = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackFrame",
  () => [
    { no: 1, name: "payload", kind: "scalar", T: 12 /* ScalarType.BYTES */, req: true },
    { no: 2, name: "user_timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.DataTrackError
 */
const DataTrackError = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackError",
  () => [
    { no: 1, name: "code", kind: "enum", T: proto2.getEnumType(DataTrackErrorCode), req: true },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishDataTrackError
 */
const PublishDataTrackError = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishDataTrackError",
  () => [
    { no: 1, name: "code", kind: "enum", T: proto2.getEnumType(PublishDataTrackErrorCode), req: true },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.LocalDataTrackTryPushError
 */
const LocalDataTrackTryPushError = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalDataTrackTryPushError",
  () => [
    { no: 1, name: "code", kind: "enum", T: proto2.getEnumType(LocalDataTrackTryPushErrorCode), req: true },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SubscribeDataTrackError
 */
const SubscribeDataTrackError = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SubscribeDataTrackError",
  () => [
    { no: 1, name: "code", kind: "enum", T: proto2.getEnumType(SubscribeDataTrackErrorCode), req: true },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * Options for publishing a data track.
 *
 * @generated from message livekit.proto.DataTrackOptions
 */
const DataTrackOptions = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackOptions",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * Publish a data track
 *
 * @generated from message livekit.proto.PublishDataTrackRequest
 */
const PublishDataTrackRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishDataTrackRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "options", kind: "message", T: DataTrackOptions, req: true },
    { no: 3, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishDataTrackResponse
 */
const PublishDataTrackResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishDataTrackResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishDataTrackCallback
 */
const PublishDataTrackCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishDataTrackCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "track", kind: "message", T: OwnedLocalDataTrack, oneof: "result" },
    { no: 3, name: "error", kind: "message", T: PublishDataTrackError, oneof: "result" },
  ],
);

/**
 * @generated from message livekit.proto.OwnedLocalDataTrack
 */
const OwnedLocalDataTrack = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.OwnedLocalDataTrack",
  () => [
    { no: 1, name: "handle", kind: "message", T: FfiOwnedHandle, req: true },
    { no: 2, name: "info", kind: "message", T: DataTrackInfo, req: true },
  ],
);

/**
 * Try pushing a frame to subscribers of the track.
 *
 * @generated from message livekit.proto.LocalDataTrackTryPushRequest
 */
const LocalDataTrackTryPushRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalDataTrackTryPushRequest",
  () => [
    { no: 1, name: "track_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "frame", kind: "message", T: DataTrackFrame, req: true },
  ],
);

/**
 * @generated from message livekit.proto.LocalDataTrackTryPushResponse
 */
const LocalDataTrackTryPushResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalDataTrackTryPushResponse",
  () => [
    { no: 2, name: "error", kind: "message", T: LocalDataTrackTryPushError, opt: true },
  ],
);

/**
 * Checks if the track is still published.
 *
 * @generated from message livekit.proto.LocalDataTrackIsPublishedRequest
 */
const LocalDataTrackIsPublishedRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalDataTrackIsPublishedRequest",
  () => [
    { no: 1, name: "track_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.LocalDataTrackIsPublishedResponse
 */
const LocalDataTrackIsPublishedResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalDataTrackIsPublishedResponse",
  () => [
    { no: 1, name: "is_published", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * Unpublishes the track.
 *
 * @generated from message livekit.proto.LocalDataTrackUnpublishRequest
 */
const LocalDataTrackUnpublishRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalDataTrackUnpublishRequest",
  () => [
    { no: 1, name: "track_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.LocalDataTrackUnpublishResponse
 */
const LocalDataTrackUnpublishResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalDataTrackUnpublishResponse",
  [],
);

/**
 * @generated from message livekit.proto.OwnedRemoteDataTrack
 */
const OwnedRemoteDataTrack = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.OwnedRemoteDataTrack",
  () => [
    { no: 1, name: "handle", kind: "message", T: FfiOwnedHandle, req: true },
    { no: 2, name: "info", kind: "message", T: DataTrackInfo, req: true },
    { no: 3, name: "publisher_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * Handle to an active data track subscription.
 *
 * Dropping the handle will unsubscribe from the track.
 *
 *
 * @generated from message livekit.proto.OwnedDataTrackStream
 */
const OwnedDataTrackStream = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.OwnedDataTrackStream",
  () => [
    { no: 1, name: "handle", kind: "message", T: FfiOwnedHandle, req: true },
  ],
);

/**
 * Reserved for future subscription options.
 *
 * @generated from message livekit.proto.DataTrackSubscribeOptions
 */
const DataTrackSubscribeOptions = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackSubscribeOptions",
  () => [
    { no: 1, name: "buffer_size", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
  ],
);

/**
 * Checks if the track is still published.
 *
 * @generated from message livekit.proto.RemoteDataTrackIsPublishedRequest
 */
const RemoteDataTrackIsPublishedRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RemoteDataTrackIsPublishedRequest",
  () => [
    { no: 1, name: "track_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.RemoteDataTrackIsPublishedResponse
 */
const RemoteDataTrackIsPublishedResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RemoteDataTrackIsPublishedResponse",
  () => [
    { no: 1, name: "is_published", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * Subscribe to a data track.
 *
 * @generated from message livekit.proto.SubscribeDataTrackRequest
 */
const SubscribeDataTrackRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SubscribeDataTrackRequest",
  () => [
    { no: 1, name: "track_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "options", kind: "message", T: DataTrackSubscribeOptions, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SubscribeDataTrackResponse
 */
const SubscribeDataTrackResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SubscribeDataTrackResponse",
  () => [
    { no: 1, name: "stream", kind: "message", T: OwnedDataTrackStream, req: true },
  ],
);

/**
 * Signal readiness to handle the next frame.
 *
 * This allows the client to put backpressure on the internal receive buffer.
 * Sending this request will cause the next frame to be sent via `DataTrackStreamFrameReceived`
 * once one is available.
 *
 *
 * @generated from message livekit.proto.DataTrackStreamReadRequest
 */
const DataTrackStreamReadRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackStreamReadRequest",
  () => [
    { no: 1, name: "stream_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.DataTrackStreamReadResponse
 */
const DataTrackStreamReadResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackStreamReadResponse",
  [],
);

/**
 * Event emitted on an active stream.
 *
 * @generated from message livekit.proto.DataTrackStreamEvent
 */
const DataTrackStreamEvent = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackStreamEvent",
  () => [
    { no: 1, name: "stream_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "frame_received", kind: "message", T: DataTrackStreamFrameReceived, oneof: "detail" },
    { no: 3, name: "eos", kind: "message", T: DataTrackStreamEOS, oneof: "detail" },
  ],
);

/**
 * A frame was received.
 *
 * @generated from message livekit.proto.DataTrackStreamFrameReceived
 */
const DataTrackStreamFrameReceived = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackStreamFrameReceived",
  () => [
    { no: 1, name: "frame", kind: "message", T: DataTrackFrame, req: true },
  ],
);

/**
 * Stream has ended.
 *
 * @generated from message livekit.proto.DataTrackStreamEOS
 */
const DataTrackStreamEOS = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataTrackStreamEOS",
  () => [
    { no: 1, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);


exports.DataTrackErrorCode = DataTrackErrorCode;
exports.PublishDataTrackErrorCode = PublishDataTrackErrorCode;
exports.LocalDataTrackTryPushErrorCode = LocalDataTrackTryPushErrorCode;
exports.SubscribeDataTrackErrorCode = SubscribeDataTrackErrorCode;
exports.DataTrackInfo = DataTrackInfo;
exports.DataTrackFrame = DataTrackFrame;
exports.DataTrackError = DataTrackError;
exports.PublishDataTrackError = PublishDataTrackError;
exports.LocalDataTrackTryPushError = LocalDataTrackTryPushError;
exports.SubscribeDataTrackError = SubscribeDataTrackError;
exports.DataTrackOptions = DataTrackOptions;
exports.PublishDataTrackRequest = PublishDataTrackRequest;
exports.PublishDataTrackResponse = PublishDataTrackResponse;
exports.PublishDataTrackCallback = PublishDataTrackCallback;
exports.OwnedLocalDataTrack = OwnedLocalDataTrack;
exports.LocalDataTrackTryPushRequest = LocalDataTrackTryPushRequest;
exports.LocalDataTrackTryPushResponse = LocalDataTrackTryPushResponse;
exports.LocalDataTrackIsPublishedRequest = LocalDataTrackIsPublishedRequest;
exports.LocalDataTrackIsPublishedResponse = LocalDataTrackIsPublishedResponse;
exports.LocalDataTrackUnpublishRequest = LocalDataTrackUnpublishRequest;
exports.LocalDataTrackUnpublishResponse = LocalDataTrackUnpublishResponse;
exports.OwnedRemoteDataTrack = OwnedRemoteDataTrack;
exports.OwnedDataTrackStream = OwnedDataTrackStream;
exports.DataTrackSubscribeOptions = DataTrackSubscribeOptions;
exports.RemoteDataTrackIsPublishedRequest = RemoteDataTrackIsPublishedRequest;
exports.RemoteDataTrackIsPublishedResponse = RemoteDataTrackIsPublishedResponse;
exports.SubscribeDataTrackRequest = SubscribeDataTrackRequest;
exports.SubscribeDataTrackResponse = SubscribeDataTrackResponse;
exports.DataTrackStreamReadRequest = DataTrackStreamReadRequest;
exports.DataTrackStreamReadResponse = DataTrackStreamReadResponse;
exports.DataTrackStreamEvent = DataTrackStreamEvent;
exports.DataTrackStreamFrameReceived = DataTrackStreamFrameReceived;
exports.DataTrackStreamEOS = DataTrackStreamEOS;
