// Copyright 2025 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file e2ee.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { proto2 } = require("@bufbuild/protobuf");

/**
 * @generated from enum livekit.proto.EncryptionType
 */
const EncryptionType = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.EncryptionType",
  [
    {no: 0, name: "NONE"},
    {no: 1, name: "GCM"},
    {no: 2, name: "CUSTOM"},
  ],
);

/**
 * @generated from enum livekit.proto.EncryptionState
 */
const EncryptionState = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.EncryptionState",
  [
    {no: 0, name: "NEW"},
    {no: 1, name: "OK"},
    {no: 2, name: "ENCRYPTION_FAILED"},
    {no: 3, name: "DECRYPTION_FAILED"},
    {no: 4, name: "MISSING_KEY"},
    {no: 5, name: "KEY_RATCHETED"},
    {no: 6, name: "INTERNAL_ERROR"},
  ],
);

/**
 * @generated from message livekit.proto.FrameCryptor
 */
const FrameCryptor = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.FrameCryptor",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
    { no: 4, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.KeyProviderOptions
 */
const KeyProviderOptions = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.KeyProviderOptions",
  () => [
    { no: 1, name: "shared_key", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
    { no: 2, name: "ratchet_window_size", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
    { no: 3, name: "ratchet_salt", kind: "scalar", T: 12 /* ScalarType.BYTES */, req: true },
    { no: 4, name: "failure_tolerance", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.E2eeOptions
 */
const E2eeOptions = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeOptions",
  () => [
    { no: 1, name: "encryption_type", kind: "enum", T: proto2.getEnumType(EncryptionType), req: true },
    { no: 2, name: "key_provider_options", kind: "message", T: KeyProviderOptions, req: true },
  ],
);

/**
 * @generated from message livekit.proto.E2eeManagerSetEnabledRequest
 */
const E2eeManagerSetEnabledRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeManagerSetEnabledRequest",
  () => [
    { no: 1, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.E2eeManagerSetEnabledResponse
 */
const E2eeManagerSetEnabledResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeManagerSetEnabledResponse",
  [],
);

/**
 * @generated from message livekit.proto.E2eeManagerGetFrameCryptorsRequest
 */
const E2eeManagerGetFrameCryptorsRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeManagerGetFrameCryptorsRequest",
  [],
);

/**
 * @generated from message livekit.proto.E2eeManagerGetFrameCryptorsResponse
 */
const E2eeManagerGetFrameCryptorsResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeManagerGetFrameCryptorsResponse",
  () => [
    { no: 1, name: "frame_cryptors", kind: "message", T: FrameCryptor, repeated: true },
  ],
);

/**
 * @generated from message livekit.proto.FrameCryptorSetEnabledRequest
 */
const FrameCryptorSetEnabledRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.FrameCryptorSetEnabledRequest",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.FrameCryptorSetEnabledResponse
 */
const FrameCryptorSetEnabledResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.FrameCryptorSetEnabledResponse",
  [],
);

/**
 * @generated from message livekit.proto.FrameCryptorSetKeyIndexRequest
 */
const FrameCryptorSetKeyIndexRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.FrameCryptorSetKeyIndexRequest",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.FrameCryptorSetKeyIndexResponse
 */
const FrameCryptorSetKeyIndexResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.FrameCryptorSetKeyIndexResponse",
  [],
);

/**
 * @generated from message livekit.proto.SetSharedKeyRequest
 */
const SetSharedKeyRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetSharedKeyRequest",
  () => [
    { no: 1, name: "shared_key", kind: "scalar", T: 12 /* ScalarType.BYTES */, req: true },
    { no: 2, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetSharedKeyResponse
 */
const SetSharedKeyResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetSharedKeyResponse",
  [],
);

/**
 * @generated from message livekit.proto.RatchetSharedKeyRequest
 */
const RatchetSharedKeyRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RatchetSharedKeyRequest",
  () => [
    { no: 1, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.RatchetSharedKeyResponse
 */
const RatchetSharedKeyResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RatchetSharedKeyResponse",
  () => [
    { no: 1, name: "new_key", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.GetSharedKeyRequest
 */
const GetSharedKeyRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetSharedKeyRequest",
  () => [
    { no: 1, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.GetSharedKeyResponse
 */
const GetSharedKeyResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetSharedKeyResponse",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SetKeyRequest
 */
const SetKeyRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetKeyRequest",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "key", kind: "scalar", T: 12 /* ScalarType.BYTES */, req: true },
    { no: 3, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetKeyResponse
 */
const SetKeyResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetKeyResponse",
  [],
);

/**
 * @generated from message livekit.proto.RatchetKeyRequest
 */
const RatchetKeyRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RatchetKeyRequest",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.RatchetKeyResponse
 */
const RatchetKeyResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RatchetKeyResponse",
  () => [
    { no: 1, name: "new_key", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.GetKeyRequest
 */
const GetKeyRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetKeyRequest",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "key_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.GetKeyResponse
 */
const GetKeyResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetKeyResponse",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.E2eeRequest
 */
const E2eeRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeRequest",
  () => [
    { no: 1, name: "room_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "manager_set_enabled", kind: "message", T: E2eeManagerSetEnabledRequest, oneof: "message" },
    { no: 3, name: "manager_get_frame_cryptors", kind: "message", T: E2eeManagerGetFrameCryptorsRequest, oneof: "message" },
    { no: 4, name: "cryptor_set_enabled", kind: "message", T: FrameCryptorSetEnabledRequest, oneof: "message" },
    { no: 5, name: "cryptor_set_key_index", kind: "message", T: FrameCryptorSetKeyIndexRequest, oneof: "message" },
    { no: 6, name: "set_shared_key", kind: "message", T: SetSharedKeyRequest, oneof: "message" },
    { no: 7, name: "ratchet_shared_key", kind: "message", T: RatchetSharedKeyRequest, oneof: "message" },
    { no: 8, name: "get_shared_key", kind: "message", T: GetSharedKeyRequest, oneof: "message" },
    { no: 9, name: "set_key", kind: "message", T: SetKeyRequest, oneof: "message" },
    { no: 10, name: "ratchet_key", kind: "message", T: RatchetKeyRequest, oneof: "message" },
    { no: 11, name: "get_key", kind: "message", T: GetKeyRequest, oneof: "message" },
  ],
);

/**
 * @generated from message livekit.proto.E2eeResponse
 */
const E2eeResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeResponse",
  () => [
    { no: 1, name: "manager_set_enabled", kind: "message", T: E2eeManagerSetEnabledResponse, oneof: "message" },
    { no: 2, name: "manager_get_frame_cryptors", kind: "message", T: E2eeManagerGetFrameCryptorsResponse, oneof: "message" },
    { no: 3, name: "cryptor_set_enabled", kind: "message", T: FrameCryptorSetEnabledResponse, oneof: "message" },
    { no: 4, name: "cryptor_set_key_index", kind: "message", T: FrameCryptorSetKeyIndexResponse, oneof: "message" },
    { no: 5, name: "set_shared_key", kind: "message", T: SetSharedKeyResponse, oneof: "message" },
    { no: 6, name: "ratchet_shared_key", kind: "message", T: RatchetSharedKeyResponse, oneof: "message" },
    { no: 7, name: "get_shared_key", kind: "message", T: GetSharedKeyResponse, oneof: "message" },
    { no: 8, name: "set_key", kind: "message", T: SetKeyResponse, oneof: "message" },
    { no: 9, name: "ratchet_key", kind: "message", T: RatchetKeyResponse, oneof: "message" },
    { no: 10, name: "get_key", kind: "message", T: GetKeyResponse, oneof: "message" },
  ],
);


exports.EncryptionType = EncryptionType;
exports.EncryptionState = EncryptionState;
exports.FrameCryptor = FrameCryptor;
exports.KeyProviderOptions = KeyProviderOptions;
exports.E2eeOptions = E2eeOptions;
exports.E2eeManagerSetEnabledRequest = E2eeManagerSetEnabledRequest;
exports.E2eeManagerSetEnabledResponse = E2eeManagerSetEnabledResponse;
exports.E2eeManagerGetFrameCryptorsRequest = E2eeManagerGetFrameCryptorsRequest;
exports.E2eeManagerGetFrameCryptorsResponse = E2eeManagerGetFrameCryptorsResponse;
exports.FrameCryptorSetEnabledRequest = FrameCryptorSetEnabledRequest;
exports.FrameCryptorSetEnabledResponse = FrameCryptorSetEnabledResponse;
exports.FrameCryptorSetKeyIndexRequest = FrameCryptorSetKeyIndexRequest;
exports.FrameCryptorSetKeyIndexResponse = FrameCryptorSetKeyIndexResponse;
exports.SetSharedKeyRequest = SetSharedKeyRequest;
exports.SetSharedKeyResponse = SetSharedKeyResponse;
exports.RatchetSharedKeyRequest = RatchetSharedKeyRequest;
exports.RatchetSharedKeyResponse = RatchetSharedKeyResponse;
exports.GetSharedKeyRequest = GetSharedKeyRequest;
exports.GetSharedKeyResponse = GetSharedKeyResponse;
exports.SetKeyRequest = SetKeyRequest;
exports.SetKeyResponse = SetKeyResponse;
exports.RatchetKeyRequest = RatchetKeyRequest;
exports.RatchetKeyResponse = RatchetKeyResponse;
exports.GetKeyRequest = GetKeyRequest;
exports.GetKeyResponse = GetKeyResponse;
exports.E2eeRequest = E2eeRequest;
exports.E2eeResponse = E2eeResponse;
