// Copyright 2025 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file participant.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { proto2 } = require("@bufbuild/protobuf");
const { FfiOwnedHandle } = require("./handle_pb.js");
const { TrackSource } = require("./track_pb.js");

/**
 * @generated from enum livekit.proto.ParticipantKind
 */
const ParticipantKind = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.ParticipantKind",
  [
    {no: 0, name: "PARTICIPANT_KIND_STANDARD", localName: "STANDARD"},
    {no: 1, name: "PARTICIPANT_KIND_INGRESS", localName: "INGRESS"},
    {no: 2, name: "PARTICIPANT_KIND_EGRESS", localName: "EGRESS"},
    {no: 3, name: "PARTICIPANT_KIND_SIP", localName: "SIP"},
    {no: 4, name: "PARTICIPANT_KIND_AGENT", localName: "AGENT"},
    {no: 5, name: "PARTICIPANT_KIND_CONNECTOR", localName: "CONNECTOR"},
    {no: 6, name: "PARTICIPANT_KIND_BRIDGE", localName: "BRIDGE"},
  ],
);

/**
 * @generated from enum livekit.proto.ParticipantKindDetail
 */
const ParticipantKindDetail = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.ParticipantKindDetail",
  [
    {no: 0, name: "PARTICIPANT_KIND_DETAIL_CLOUD_AGENT", localName: "CLOUD_AGENT"},
    {no: 1, name: "PARTICIPANT_KIND_DETAIL_FORWARDED", localName: "FORWARDED"},
    {no: 2, name: "PARTICIPANT_KIND_DETAIL_CONNECTOR_WHATSAPP", localName: "CONNECTOR_WHATSAPP"},
    {no: 3, name: "PARTICIPANT_KIND_DETAIL_CONNECTOR_TWILIO", localName: "CONNECTOR_TWILIO"},
    {no: 4, name: "PARTICIPANT_KIND_DETAIL_BRIDGE_RTSP", localName: "BRIDGE_RTSP"},
  ],
);

/**
 * @generated from enum livekit.proto.DisconnectReason
 */
const DisconnectReason = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.DisconnectReason",
  [
    {no: 0, name: "UNKNOWN_REASON"},
    {no: 1, name: "CLIENT_INITIATED"},
    {no: 2, name: "DUPLICATE_IDENTITY"},
    {no: 3, name: "SERVER_SHUTDOWN"},
    {no: 4, name: "PARTICIPANT_REMOVED"},
    {no: 5, name: "ROOM_DELETED"},
    {no: 6, name: "STATE_MISMATCH"},
    {no: 7, name: "JOIN_FAILURE"},
    {no: 8, name: "MIGRATION"},
    {no: 9, name: "SIGNAL_CLOSE"},
    {no: 10, name: "ROOM_CLOSED"},
    {no: 11, name: "USER_UNAVAILABLE"},
    {no: 12, name: "USER_REJECTED"},
    {no: 13, name: "SIP_TRUNK_FAILURE"},
    {no: 14, name: "CONNECTION_TIMEOUT"},
    {no: 15, name: "MEDIA_FAILURE"},
  ],
);

/**
 * @generated from message livekit.proto.ParticipantInfo
 */
const ParticipantInfo = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantInfo",
  () => [
    { no: 1, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 4, name: "metadata", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 5, name: "attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 6, name: "kind", kind: "enum", T: proto2.getEnumType(ParticipantKind), req: true },
    { no: 7, name: "disconnect_reason", kind: "enum", T: proto2.getEnumType(DisconnectReason), req: true },
    { no: 8, name: "kind_details", kind: "enum", T: proto2.getEnumType(ParticipantKindDetail), repeated: true },
    { no: 9, name: "permission", kind: "message", T: ParticipantPermission, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.OwnedParticipant
 */
const OwnedParticipant = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.OwnedParticipant",
  () => [
    { no: 1, name: "handle", kind: "message", T: FfiOwnedHandle, req: true },
    { no: 2, name: "info", kind: "message", T: ParticipantInfo, req: true },
  ],
);

/**
 * copied from livekit-protocol/protocol/protobufs/livekit_models.proto and removed deprecated fields
 *
 * @generated from message livekit.proto.ParticipantPermission
 */
const ParticipantPermission = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantPermission",
  () => [
    { no: 1, name: "can_subscribe", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 2, name: "can_publish", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 3, name: "can_publish_data", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 9, name: "can_publish_sources", kind: "enum", T: proto2.getEnumType(TrackSource), repeated: true },
    { no: 7, name: "hidden", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 10, name: "can_update_metadata", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 12, name: "can_subscribe_metrics", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);


exports.ParticipantKind = ParticipantKind;
exports.ParticipantKindDetail = ParticipantKindDetail;
exports.DisconnectReason = DisconnectReason;
exports.ParticipantInfo = ParticipantInfo;
exports.OwnedParticipant = OwnedParticipant;
exports.ParticipantPermission = ParticipantPermission;
