// Copyright 2025 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file participant.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto2 } from "@bufbuild/protobuf";
import type { FfiOwnedHandle } from "./handle_pb.js";
import type { TrackSource } from "./track_pb.js";

/**
 * @generated from enum livekit.proto.ParticipantKind
 */
export declare enum ParticipantKind {
  /**
   * @generated from enum value: PARTICIPANT_KIND_STANDARD = 0;
   */
  STANDARD = 0,

  /**
   * @generated from enum value: PARTICIPANT_KIND_INGRESS = 1;
   */
  INGRESS = 1,

  /**
   * @generated from enum value: PARTICIPANT_KIND_EGRESS = 2;
   */
  EGRESS = 2,

  /**
   * @generated from enum value: PARTICIPANT_KIND_SIP = 3;
   */
  SIP = 3,

  /**
   * @generated from enum value: PARTICIPANT_KIND_AGENT = 4;
   */
  AGENT = 4,

  /**
   * @generated from enum value: PARTICIPANT_KIND_CONNECTOR = 5;
   */
  CONNECTOR = 5,

  /**
   * @generated from enum value: PARTICIPANT_KIND_BRIDGE = 6;
   */
  BRIDGE = 6,
}

/**
 * @generated from enum livekit.proto.ParticipantKindDetail
 */
export declare enum ParticipantKindDetail {
  /**
   * @generated from enum value: PARTICIPANT_KIND_DETAIL_CLOUD_AGENT = 0;
   */
  CLOUD_AGENT = 0,

  /**
   * @generated from enum value: PARTICIPANT_KIND_DETAIL_FORWARDED = 1;
   */
  FORWARDED = 1,

  /**
   * @generated from enum value: PARTICIPANT_KIND_DETAIL_CONNECTOR_WHATSAPP = 2;
   */
  CONNECTOR_WHATSAPP = 2,

  /**
   * @generated from enum value: PARTICIPANT_KIND_DETAIL_CONNECTOR_TWILIO = 3;
   */
  CONNECTOR_TWILIO = 3,

  /**
   * @generated from enum value: PARTICIPANT_KIND_DETAIL_BRIDGE_RTSP = 4;
   */
  BRIDGE_RTSP = 4,
}

/**
 * @generated from enum livekit.proto.DisconnectReason
 */
export declare enum DisconnectReason {
  /**
   * @generated from enum value: UNKNOWN_REASON = 0;
   */
  UNKNOWN_REASON = 0,

  /**
   * the client initiated the disconnect
   *
   * @generated from enum value: CLIENT_INITIATED = 1;
   */
  CLIENT_INITIATED = 1,

  /**
   * another participant with the same identity has joined the room
   *
   * @generated from enum value: DUPLICATE_IDENTITY = 2;
   */
  DUPLICATE_IDENTITY = 2,

  /**
   * the server instance is shutting down
   *
   * @generated from enum value: SERVER_SHUTDOWN = 3;
   */
  SERVER_SHUTDOWN = 3,

  /**
   * RoomService.RemoveParticipant was called
   *
   * @generated from enum value: PARTICIPANT_REMOVED = 4;
   */
  PARTICIPANT_REMOVED = 4,

  /**
   * RoomService.DeleteRoom was called
   *
   * @generated from enum value: ROOM_DELETED = 5;
   */
  ROOM_DELETED = 5,

  /**
   * the client is attempting to resume a session, but server is not aware of it
   *
   * @generated from enum value: STATE_MISMATCH = 6;
   */
  STATE_MISMATCH = 6,

  /**
   * client was unable to connect fully
   *
   * @generated from enum value: JOIN_FAILURE = 7;
   */
  JOIN_FAILURE = 7,

  /**
   * Cloud-only, the server requested Participant to migrate the connection elsewhere
   *
   * @generated from enum value: MIGRATION = 8;
   */
  MIGRATION = 8,

  /**
   * the signal websocket was closed unexpectedly
   *
   * @generated from enum value: SIGNAL_CLOSE = 9;
   */
  SIGNAL_CLOSE = 9,

  /**
   * the room was closed, due to all Standard and Ingress participants having left
   *
   * @generated from enum value: ROOM_CLOSED = 10;
   */
  ROOM_CLOSED = 10,

  /**
   * SIP callee did not respond in time
   *
   * @generated from enum value: USER_UNAVAILABLE = 11;
   */
  USER_UNAVAILABLE = 11,

  /**
   * SIP callee rejected the call (busy)
   *
   * @generated from enum value: USER_REJECTED = 12;
   */
  USER_REJECTED = 12,

  /**
   * SIP protocol failure or unexpected response
   *
   * @generated from enum value: SIP_TRUNK_FAILURE = 13;
   */
  SIP_TRUNK_FAILURE = 13,

  /**
   * @generated from enum value: CONNECTION_TIMEOUT = 14;
   */
  CONNECTION_TIMEOUT = 14,

  /**
   * @generated from enum value: MEDIA_FAILURE = 15;
   */
  MEDIA_FAILURE = 15,
}

/**
 * @generated from message livekit.proto.ParticipantInfo
 */
export declare class ParticipantInfo extends Message<ParticipantInfo> {
  /**
   * @generated from field: required string sid = 1;
   */
  sid?: string;

  /**
   * @generated from field: required string name = 2;
   */
  name?: string;

  /**
   * @generated from field: required string identity = 3;
   */
  identity?: string;

  /**
   * @generated from field: required string metadata = 4;
   */
  metadata?: string;

  /**
   * @generated from field: map<string, string> attributes = 5;
   */
  attributes: { [key: string]: string };

  /**
   * @generated from field: required livekit.proto.ParticipantKind kind = 6;
   */
  kind?: ParticipantKind;

  /**
   * @generated from field: required livekit.proto.DisconnectReason disconnect_reason = 7;
   */
  disconnectReason?: DisconnectReason;

  /**
   * @generated from field: repeated livekit.proto.ParticipantKindDetail kind_details = 8;
   */
  kindDetails: ParticipantKindDetail[];

  /**
   * @generated from field: optional livekit.proto.ParticipantPermission permission = 9;
   */
  permission?: ParticipantPermission;

  constructor(data?: PartialMessage<ParticipantInfo>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.ParticipantInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ParticipantInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ParticipantInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ParticipantInfo;

  static equals(a: ParticipantInfo | PlainMessage<ParticipantInfo> | undefined, b: ParticipantInfo | PlainMessage<ParticipantInfo> | undefined): boolean;
}

/**
 * @generated from message livekit.proto.OwnedParticipant
 */
export declare class OwnedParticipant extends Message<OwnedParticipant> {
  /**
   * @generated from field: required livekit.proto.FfiOwnedHandle handle = 1;
   */
  handle?: FfiOwnedHandle;

  /**
   * @generated from field: required livekit.proto.ParticipantInfo info = 2;
   */
  info?: ParticipantInfo;

  constructor(data?: PartialMessage<OwnedParticipant>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.OwnedParticipant";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OwnedParticipant;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OwnedParticipant;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OwnedParticipant;

  static equals(a: OwnedParticipant | PlainMessage<OwnedParticipant> | undefined, b: OwnedParticipant | PlainMessage<OwnedParticipant> | undefined): boolean;
}

/**
 * copied from livekit-protocol/protocol/protobufs/livekit_models.proto and removed deprecated fields
 *
 * @generated from message livekit.proto.ParticipantPermission
 */
export declare class ParticipantPermission extends Message<ParticipantPermission> {
  /**
   * allow participant to subscribe to other tracks in the room
   *
   * @generated from field: required bool can_subscribe = 1;
   */
  canSubscribe?: boolean;

  /**
   * allow participant to publish new tracks to room
   *
   * @generated from field: required bool can_publish = 2;
   */
  canPublish?: boolean;

  /**
   * allow participant to publish data
   *
   * @generated from field: required bool can_publish_data = 3;
   */
  canPublishData?: boolean;

  /**
   * sources that are allowed to be published
   *
   * @generated from field: repeated livekit.proto.TrackSource can_publish_sources = 9;
   */
  canPublishSources: TrackSource[];

  /**
   * indicates that it's hidden to others
   *
   * @generated from field: required bool hidden = 7;
   */
  hidden?: boolean;

  /**
   * indicates that participant can update own metadata and attributes
   *
   * @generated from field: required bool can_update_metadata = 10;
   */
  canUpdateMetadata?: boolean;

  /**
   * if a participant can subscribe to metrics
   *
   * @generated from field: required bool can_subscribe_metrics = 12;
   */
  canSubscribeMetrics?: boolean;

  constructor(data?: PartialMessage<ParticipantPermission>);

  static readonly runtime: typeof proto2;
  static readonly typeName = "livekit.proto.ParticipantPermission";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ParticipantPermission;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ParticipantPermission;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ParticipantPermission;

  static equals(a: ParticipantPermission | PlainMessage<ParticipantPermission> | undefined, b: ParticipantPermission | PlainMessage<ParticipantPermission> | undefined): boolean;
}

