// Copyright 2025 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.1 with parameter "js_import_style=legacy_commonjs"
// @generated from file room.proto (package livekit.proto, syntax proto2)
/* eslint-disable */
// @ts-nocheck

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { proto2 } = require("@bufbuild/protobuf");
const { DisconnectReason, OwnedParticipant, ParticipantInfo, ParticipantPermission } = require("./participant_pb.js");
const { OwnedTrack, OwnedTrackPublication, TrackSource } = require("./track_pb.js");
const { RtcStats } = require("./stats_pb.js");
const { VideoCodec } = require("./video_frame_pb.js");
const { E2eeOptions, EncryptionState } = require("./e2ee_pb.js");
const { FfiOwnedHandle } = require("./handle_pb.js");
const { OwnedByteStreamReader, OwnedTextStreamReader } = require("./data_stream_pb.js");

/**
 * @generated from enum livekit.proto.IceTransportType
 */
const IceTransportType = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.IceTransportType",
  [
    {no: 0, name: "TRANSPORT_RELAY"},
    {no: 1, name: "TRANSPORT_NOHOST"},
    {no: 2, name: "TRANSPORT_ALL"},
  ],
);

/**
 * @generated from enum livekit.proto.ContinualGatheringPolicy
 */
const ContinualGatheringPolicy = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.ContinualGatheringPolicy",
  [
    {no: 0, name: "GATHER_ONCE"},
    {no: 1, name: "GATHER_CONTINUALLY"},
  ],
);

/**
 * @generated from enum livekit.proto.ConnectionQuality
 */
const ConnectionQuality = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.ConnectionQuality",
  [
    {no: 0, name: "QUALITY_POOR"},
    {no: 1, name: "QUALITY_GOOD"},
    {no: 2, name: "QUALITY_EXCELLENT"},
    {no: 3, name: "QUALITY_LOST"},
  ],
);

/**
 * @generated from enum livekit.proto.ConnectionState
 */
const ConnectionState = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.ConnectionState",
  [
    {no: 0, name: "CONN_DISCONNECTED"},
    {no: 1, name: "CONN_CONNECTED"},
    {no: 2, name: "CONN_RECONNECTING"},
  ],
);

/**
 * @generated from enum livekit.proto.DataPacketKind
 */
const DataPacketKind = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.DataPacketKind",
  [
    {no: 0, name: "KIND_LOSSY"},
    {no: 1, name: "KIND_RELIABLE"},
  ],
);

/**
 * Connect to a new LiveKit room
 *
 * @generated from message livekit.proto.ConnectRequest
 */
const ConnectRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ConnectRequest",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "options", kind: "message", T: RoomOptions, req: true },
    { no: 4, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.ConnectResponse
 */
const ConnectResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ConnectResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ConnectCallback
 */
const ConnectCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ConnectCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message" },
    { no: 3, name: "result", kind: "message", T: ConnectCallback_Result, oneof: "message" },
  ],
);

/**
 * @generated from message livekit.proto.ConnectCallback.ParticipantWithTracks
 */
const ConnectCallback_ParticipantWithTracks = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ConnectCallback.ParticipantWithTracks",
  () => [
    { no: 1, name: "participant", kind: "message", T: OwnedParticipant, req: true },
    { no: 2, name: "publications", kind: "message", T: OwnedTrackPublication, repeated: true },
  ],
  {localName: "ConnectCallback_ParticipantWithTracks"},
);

/**
 * @generated from message livekit.proto.ConnectCallback.Result
 */
const ConnectCallback_Result = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ConnectCallback.Result",
  () => [
    { no: 1, name: "room", kind: "message", T: OwnedRoom, req: true },
    { no: 2, name: "local_participant", kind: "message", T: OwnedParticipant, req: true },
    { no: 3, name: "participants", kind: "message", T: ConnectCallback_ParticipantWithTracks, repeated: true },
  ],
  {localName: "ConnectCallback_Result"},
);

/**
 * Disconnect from the a room
 *
 * @generated from message livekit.proto.DisconnectRequest
 */
const DisconnectRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DisconnectRequest",
  () => [
    { no: 1, name: "room_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.DisconnectResponse
 */
const DisconnectResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DisconnectResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.DisconnectCallback
 */
const DisconnectCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DisconnectCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * Publish a track to the room
 *
 * @generated from message livekit.proto.PublishTrackRequest
 */
const PublishTrackRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishTrackRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "track_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 3, name: "options", kind: "message", T: TrackPublishOptions, req: true },
    { no: 4, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishTrackResponse
 */
const PublishTrackResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishTrackResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishTrackCallback
 */
const PublishTrackCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishTrackCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message" },
    { no: 3, name: "publication", kind: "message", T: OwnedTrackPublication, oneof: "message" },
  ],
);

/**
 * Unpublish a track from the room
 *
 * @generated from message livekit.proto.UnpublishTrackRequest
 */
const UnpublishTrackRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.UnpublishTrackRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "stop_on_unpublish", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 4, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.UnpublishTrackResponse
 */
const UnpublishTrackResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.UnpublishTrackResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.UnpublishTrackCallback
 */
const UnpublishTrackCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.UnpublishTrackCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * Publish data to other participants
 *
 * @generated from message livekit.proto.PublishDataRequest
 */
const PublishDataRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishDataRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "data_ptr", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 3, name: "data_len", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 4, name: "reliable", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 5, name: "destination_sids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: "topic", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "destination_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 8, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishDataResponse
 */
const PublishDataResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishDataResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishDataCallback
 */
const PublishDataCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishDataCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * Publish transcription messages to room
 *
 * @generated from message livekit.proto.PublishTranscriptionRequest
 */
const PublishTranscriptionRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishTranscriptionRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "track_id", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 4, name: "segments", kind: "message", T: TranscriptionSegment, repeated: true },
    { no: 5, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishTranscriptionResponse
 */
const PublishTranscriptionResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishTranscriptionResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishTranscriptionCallback
 */
const PublishTranscriptionCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishTranscriptionCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * Publish Sip DTMF messages to other participants
 *
 * @generated from message livekit.proto.PublishSipDtmfRequest
 */
const PublishSipDtmfRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishSipDtmfRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "code", kind: "scalar", T: 13 /* ScalarType.UINT32 */, req: true },
    { no: 3, name: "digit", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 4, name: "destination_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishSipDtmfResponse
 */
const PublishSipDtmfResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishSipDtmfResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.PublishSipDtmfCallback
 */
const PublishSipDtmfCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.PublishSipDtmfCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * Change the local participant's metadata
 *
 * @generated from message livekit.proto.SetLocalMetadataRequest
 */
const SetLocalMetadataRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalMetadataRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "metadata", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SetLocalMetadataResponse
 */
const SetLocalMetadataResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalMetadataResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetLocalMetadataCallback
 */
const SetLocalMetadataCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalMetadataCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SendChatMessageRequest
 */
const SendChatMessageRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendChatMessageRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "destination_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "sender_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.EditChatMessageRequest
 */
const EditChatMessageRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.EditChatMessageRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "edit_text", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "original_message", kind: "message", T: ChatMessage, req: true },
    { no: 4, name: "destination_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "sender_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SendChatMessageResponse
 */
const SendChatMessageResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendChatMessageResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SendChatMessageCallback
 */
const SendChatMessageCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendChatMessageCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message" },
    { no: 3, name: "chat_message", kind: "message", T: ChatMessage, oneof: "message" },
  ],
);

/**
 * Change the local participant's attributes
 *
 * @generated from message livekit.proto.SetLocalAttributesRequest
 */
const SetLocalAttributesRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalAttributesRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "attributes", kind: "message", T: AttributesEntry, repeated: true },
    { no: 3, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.AttributesEntry
 */
const AttributesEntry = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.AttributesEntry",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetLocalAttributesResponse
 */
const SetLocalAttributesResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalAttributesResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetLocalAttributesCallback
 */
const SetLocalAttributesCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalAttributesCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * Change the local participant's name
 *
 * @generated from message livekit.proto.SetLocalNameRequest
 */
const SetLocalNameRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalNameRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SetLocalNameResponse
 */
const SetLocalNameResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalNameResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetLocalNameCallback
 */
const SetLocalNameCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetLocalNameCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * Change the "desire" to subs2ribe to a track
 *
 * @generated from message livekit.proto.SetSubscribedRequest
 */
const SetSubscribedRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetSubscribedRequest",
  () => [
    { no: 1, name: "subscribe", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 2, name: "publication_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetSubscribedResponse
 */
const SetSubscribedResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetSubscribedResponse",
  [],
);

/**
 * @generated from message livekit.proto.GetSessionStatsRequest
 */
const GetSessionStatsRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetSessionStatsRequest",
  () => [
    { no: 1, name: "room_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.GetSessionStatsResponse
 */
const GetSessionStatsResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetSessionStatsResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.GetSessionStatsCallback
 */
const GetSessionStatsCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetSessionStatsCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message" },
    { no: 3, name: "result", kind: "message", T: GetSessionStatsCallback_Result, oneof: "message" },
  ],
);

/**
 * @generated from message livekit.proto.GetSessionStatsCallback.Result
 */
const GetSessionStatsCallback_Result = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.GetSessionStatsCallback.Result",
  () => [
    { no: 1, name: "publisher_stats", kind: "message", T: RtcStats, repeated: true },
    { no: 2, name: "subscriber_stats", kind: "message", T: RtcStats, repeated: true },
  ],
  {localName: "GetSessionStatsCallback_Result"},
);

/**
 * @generated from message livekit.proto.VideoEncoding
 */
const VideoEncoding = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.VideoEncoding",
  () => [
    { no: 1, name: "max_bitrate", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "max_framerate", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.AudioEncoding
 */
const AudioEncoding = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.AudioEncoding",
  () => [
    { no: 1, name: "max_bitrate", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TrackPublishOptions
 */
const TrackPublishOptions = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackPublishOptions",
  () => [
    { no: 1, name: "video_encoding", kind: "message", T: VideoEncoding, opt: true },
    { no: 2, name: "audio_encoding", kind: "message", T: AudioEncoding, opt: true },
    { no: 3, name: "video_codec", kind: "enum", T: proto2.getEnumType(VideoCodec), opt: true },
    { no: 4, name: "dtx", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: "red", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "simulcast", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "source", kind: "enum", T: proto2.getEnumType(TrackSource), opt: true },
    { no: 8, name: "stream", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "preconnect_buffer", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.IceServer
 */
const IceServer = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.IceServer",
  () => [
    { no: 1, name: "urls", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.RtcConfig
 */
const RtcConfig = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RtcConfig",
  () => [
    { no: 1, name: "ice_transport_type", kind: "enum", T: proto2.getEnumType(IceTransportType), opt: true },
    { no: 2, name: "continual_gathering_policy", kind: "enum", T: proto2.getEnumType(ContinualGatheringPolicy), opt: true },
    { no: 3, name: "ice_servers", kind: "message", T: IceServer, repeated: true },
  ],
);

/**
 * @generated from message livekit.proto.RoomOptions
 */
const RoomOptions = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RoomOptions",
  () => [
    { no: 1, name: "auto_subscribe", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 2, name: "adaptive_stream", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 3, name: "dynacast", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "e2ee", kind: "message", T: E2eeOptions, opt: true },
    { no: 5, name: "rtc_config", kind: "message", T: RtcConfig, opt: true },
    { no: 6, name: "join_retries", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 7, name: "encryption", kind: "message", T: E2eeOptions, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.TranscriptionSegment
 */
const TranscriptionSegment = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TranscriptionSegment",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "start_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 4, name: "end_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 5, name: "final", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
    { no: 6, name: "language", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.BufferInfo
 */
const BufferInfo = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.BufferInfo",
  () => [
    { no: 1, name: "data_ptr", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "data_len", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.OwnedBuffer
 */
const OwnedBuffer = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.OwnedBuffer",
  () => [
    { no: 1, name: "handle", kind: "message", T: FfiOwnedHandle, req: true },
    { no: 2, name: "data", kind: "message", T: BufferInfo, req: true },
  ],
);

/**
 * @generated from message livekit.proto.RoomEvent
 */
const RoomEvent = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RoomEvent",
  () => [
    { no: 1, name: "room_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "participant_connected", kind: "message", T: ParticipantConnected, oneof: "message" },
    { no: 3, name: "participant_disconnected", kind: "message", T: ParticipantDisconnected, oneof: "message" },
    { no: 4, name: "local_track_published", kind: "message", T: LocalTrackPublished, oneof: "message" },
    { no: 5, name: "local_track_unpublished", kind: "message", T: LocalTrackUnpublished, oneof: "message" },
    { no: 6, name: "local_track_subscribed", kind: "message", T: LocalTrackSubscribed, oneof: "message" },
    { no: 7, name: "track_published", kind: "message", T: TrackPublished, oneof: "message" },
    { no: 8, name: "track_unpublished", kind: "message", T: TrackUnpublished, oneof: "message" },
    { no: 9, name: "track_subscribed", kind: "message", T: TrackSubscribed, oneof: "message" },
    { no: 10, name: "track_unsubscribed", kind: "message", T: TrackUnsubscribed, oneof: "message" },
    { no: 11, name: "track_subscription_failed", kind: "message", T: TrackSubscriptionFailed, oneof: "message" },
    { no: 12, name: "track_muted", kind: "message", T: TrackMuted, oneof: "message" },
    { no: 13, name: "track_unmuted", kind: "message", T: TrackUnmuted, oneof: "message" },
    { no: 14, name: "active_speakers_changed", kind: "message", T: ActiveSpeakersChanged, oneof: "message" },
    { no: 15, name: "room_metadata_changed", kind: "message", T: RoomMetadataChanged, oneof: "message" },
    { no: 16, name: "room_sid_changed", kind: "message", T: RoomSidChanged, oneof: "message" },
    { no: 17, name: "participant_metadata_changed", kind: "message", T: ParticipantMetadataChanged, oneof: "message" },
    { no: 18, name: "participant_name_changed", kind: "message", T: ParticipantNameChanged, oneof: "message" },
    { no: 19, name: "participant_attributes_changed", kind: "message", T: ParticipantAttributesChanged, oneof: "message" },
    { no: 20, name: "connection_quality_changed", kind: "message", T: ConnectionQualityChanged, oneof: "message" },
    { no: 21, name: "connection_state_changed", kind: "message", T: ConnectionStateChanged, oneof: "message" },
    { no: 22, name: "disconnected", kind: "message", T: Disconnected, oneof: "message" },
    { no: 23, name: "reconnecting", kind: "message", T: Reconnecting, oneof: "message" },
    { no: 24, name: "reconnected", kind: "message", T: Reconnected, oneof: "message" },
    { no: 25, name: "e2ee_state_changed", kind: "message", T: E2eeStateChanged, oneof: "message" },
    { no: 26, name: "eos", kind: "message", T: RoomEOS, oneof: "message" },
    { no: 27, name: "data_packet_received", kind: "message", T: DataPacketReceived, oneof: "message" },
    { no: 28, name: "transcription_received", kind: "message", T: TranscriptionReceived, oneof: "message" },
    { no: 29, name: "chat_message", kind: "message", T: ChatMessageReceived, oneof: "message" },
    { no: 30, name: "stream_header_received", kind: "message", T: DataStreamHeaderReceived, oneof: "message" },
    { no: 31, name: "stream_chunk_received", kind: "message", T: DataStreamChunkReceived, oneof: "message" },
    { no: 32, name: "stream_trailer_received", kind: "message", T: DataStreamTrailerReceived, oneof: "message" },
    { no: 33, name: "data_channel_low_threshold_changed", kind: "message", T: DataChannelBufferedAmountLowThresholdChanged, oneof: "message" },
    { no: 34, name: "byte_stream_opened", kind: "message", T: ByteStreamOpened, oneof: "message" },
    { no: 35, name: "text_stream_opened", kind: "message", T: TextStreamOpened, oneof: "message" },
    { no: 36, name: "room_updated", kind: "message", T: RoomInfo, oneof: "message" },
    { no: 37, name: "moved", kind: "message", T: RoomInfo, oneof: "message" },
    { no: 38, name: "participants_updated", kind: "message", T: ParticipantsUpdated, oneof: "message" },
    { no: 39, name: "participant_encryption_status_changed", kind: "message", T: ParticipantEncryptionStatusChanged, oneof: "message" },
    { no: 41, name: "participant_permission_changed", kind: "message", T: ParticipantPermissionChanged, oneof: "message" },
    { no: 40, name: "token_refreshed", kind: "message", T: TokenRefreshed, oneof: "message" },
  ],
);

/**
 * @generated from message livekit.proto.RoomInfo
 */
const RoomInfo = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RoomInfo",
  () => [
    { no: 1, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "metadata", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 4, name: "lossy_dc_buffered_amount_low_threshold", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 5, name: "reliable_dc_buffered_amount_low_threshold", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 6, name: "empty_timeout", kind: "scalar", T: 13 /* ScalarType.UINT32 */, req: true },
    { no: 7, name: "departure_timeout", kind: "scalar", T: 13 /* ScalarType.UINT32 */, req: true },
    { no: 8, name: "max_participants", kind: "scalar", T: 13 /* ScalarType.UINT32 */, req: true },
    { no: 9, name: "creation_time", kind: "scalar", T: 3 /* ScalarType.INT64 */, req: true },
    { no: 10, name: "num_participants", kind: "scalar", T: 13 /* ScalarType.UINT32 */, req: true },
    { no: 11, name: "num_publishers", kind: "scalar", T: 13 /* ScalarType.UINT32 */, req: true },
    { no: 12, name: "active_recording", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.OwnedRoom
 */
const OwnedRoom = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.OwnedRoom",
  () => [
    { no: 1, name: "handle", kind: "message", T: FfiOwnedHandle, req: true },
    { no: 2, name: "info", kind: "message", T: RoomInfo, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantsUpdated
 */
const ParticipantsUpdated = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantsUpdated",
  () => [
    { no: 1, name: "participants", kind: "message", T: ParticipantInfo, repeated: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantConnected
 */
const ParticipantConnected = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantConnected",
  () => [
    { no: 1, name: "info", kind: "message", T: OwnedParticipant, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantDisconnected
 */
const ParticipantDisconnected = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantDisconnected",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "disconnect_reason", kind: "enum", T: proto2.getEnumType(DisconnectReason), req: true },
  ],
);

/**
 * @generated from message livekit.proto.LocalTrackPublished
 */
const LocalTrackPublished = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalTrackPublished",
  () => [
    { no: 1, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.LocalTrackUnpublished
 */
const LocalTrackUnpublished = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalTrackUnpublished",
  () => [
    { no: 1, name: "publication_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.LocalTrackSubscribed
 */
const LocalTrackSubscribed = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.LocalTrackSubscribed",
  () => [
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TrackPublished
 */
const TrackPublished = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackPublished",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "publication", kind: "message", T: OwnedTrackPublication, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TrackUnpublished
 */
const TrackUnpublished = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackUnpublished",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "publication_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * Publication isn't needed for subscription events on the FFI
 * The FFI will retrieve the publication using the Track sid
 *
 * @generated from message livekit.proto.TrackSubscribed
 */
const TrackSubscribed = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackSubscribed",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track", kind: "message", T: OwnedTrack, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TrackUnsubscribed
 */
const TrackUnsubscribed = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackUnsubscribed",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TrackSubscriptionFailed
 */
const TrackSubscriptionFailed = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackSubscriptionFailed",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TrackMuted
 */
const TrackMuted = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackMuted",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TrackUnmuted
 */
const TrackUnmuted = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TrackUnmuted",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.E2eeStateChanged
 */
const E2eeStateChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.E2eeStateChanged",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "state", kind: "enum", T: proto2.getEnumType(EncryptionState), req: true },
  ],
);

/**
 * @generated from message livekit.proto.ActiveSpeakersChanged
 */
const ActiveSpeakersChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ActiveSpeakersChanged",
  () => [
    { no: 1, name: "participant_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message livekit.proto.RoomMetadataChanged
 */
const RoomMetadataChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RoomMetadataChanged",
  () => [
    { no: 1, name: "metadata", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.RoomSidChanged
 */
const RoomSidChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RoomSidChanged",
  () => [
    { no: 1, name: "sid", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantMetadataChanged
 */
const ParticipantMetadataChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantMetadataChanged",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "metadata", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantAttributesChanged
 */
const ParticipantAttributesChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantAttributesChanged",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "attributes", kind: "message", T: AttributesEntry, repeated: true },
    { no: 3, name: "changed_attributes", kind: "message", T: AttributesEntry, repeated: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantEncryptionStatusChanged
 */
const ParticipantEncryptionStatusChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantEncryptionStatusChanged",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "is_encrypted", kind: "scalar", T: 8 /* ScalarType.BOOL */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantNameChanged
 */
const ParticipantNameChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantNameChanged",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ParticipantPermissionChanged
 */
const ParticipantPermissionChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ParticipantPermissionChanged",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "permission", kind: "message", T: ParticipantPermission, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.ConnectionQualityChanged
 */
const ConnectionQualityChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ConnectionQualityChanged",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "quality", kind: "enum", T: proto2.getEnumType(ConnectionQuality), req: true },
  ],
);

/**
 * @generated from message livekit.proto.UserPacket
 */
const UserPacket = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.UserPacket",
  () => [
    { no: 1, name: "data", kind: "message", T: OwnedBuffer, req: true },
    { no: 2, name: "topic", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.ChatMessage
 */
const ChatMessage = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ChatMessage",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */, req: true },
    { no: 3, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 4, name: "edit_timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 5, name: "deleted", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "generated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.ChatMessageReceived
 */
const ChatMessageReceived = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ChatMessageReceived",
  () => [
    { no: 1, name: "message", kind: "message", T: ChatMessage, req: true },
    { no: 2, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SipDTMF
 */
const SipDTMF = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SipDTMF",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 13 /* ScalarType.UINT32 */, req: true },
    { no: 2, name: "digit", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.DataPacketReceived
 */
const DataPacketReceived = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataPacketReceived",
  () => [
    { no: 1, name: "kind", kind: "enum", T: proto2.getEnumType(DataPacketKind), req: true },
    { no: 2, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 4, name: "user", kind: "message", T: UserPacket, oneof: "value" },
    { no: 5, name: "sip_dtmf", kind: "message", T: SipDTMF, oneof: "value" },
  ],
);

/**
 * @generated from message livekit.proto.TranscriptionReceived
 */
const TranscriptionReceived = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TranscriptionReceived",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "track_sid", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "segments", kind: "message", T: TranscriptionSegment, repeated: true },
  ],
);

/**
 * @generated from message livekit.proto.ConnectionStateChanged
 */
const ConnectionStateChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ConnectionStateChanged",
  () => [
    { no: 1, name: "state", kind: "enum", T: proto2.getEnumType(ConnectionState), req: true },
  ],
);

/**
 * @generated from message livekit.proto.Connected
 */
const Connected = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.Connected",
  [],
);

/**
 * @generated from message livekit.proto.Disconnected
 */
const Disconnected = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.Disconnected",
  () => [
    { no: 1, name: "reason", kind: "enum", T: proto2.getEnumType(DisconnectReason), req: true },
  ],
);

/**
 * @generated from message livekit.proto.Reconnecting
 */
const Reconnecting = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.Reconnecting",
  [],
);

/**
 * @generated from message livekit.proto.Reconnected
 */
const Reconnected = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.Reconnected",
  [],
);

/**
 * @generated from message livekit.proto.TokenRefreshed
 */
const TokenRefreshed = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TokenRefreshed",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.RoomEOS
 */
const RoomEOS = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.RoomEOS",
  [],
);

/**
 * @generated from message livekit.proto.DataStream
 */
const DataStream = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStream",
  [],
);

/**
 * enum for operation types (specific to TextHeader)
 *
 * @generated from enum livekit.proto.DataStream.OperationType
 */
const DataStream_OperationType = /*@__PURE__*/ proto2.makeEnum(
  "livekit.proto.DataStream.OperationType",
  [
    {no: 0, name: "CREATE"},
    {no: 1, name: "UPDATE"},
    {no: 2, name: "DELETE"},
    {no: 3, name: "REACTION"},
  ],
);

/**
 * header properties specific to text streams
 *
 * @generated from message livekit.proto.DataStream.TextHeader
 */
const DataStream_TextHeader = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStream.TextHeader",
  () => [
    { no: 1, name: "operation_type", kind: "enum", T: proto2.getEnumType(DataStream_OperationType), req: true },
    { no: 2, name: "version", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 3, name: "reply_to_stream_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "attached_stream_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "generated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
  {localName: "DataStream_TextHeader"},
);

/**
 * header properties specific to byte or file streams
 *
 * @generated from message livekit.proto.DataStream.ByteHeader
 */
const DataStream_ByteHeader = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStream.ByteHeader",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
  {localName: "DataStream_ByteHeader"},
);

/**
 * main DataStream.Header that contains a oneof for specific headers
 *
 * @generated from message livekit.proto.DataStream.Header
 */
const DataStream_Header = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStream.Header",
  () => [
    { no: 1, name: "stream_id", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */, req: true },
    { no: 3, name: "mime_type", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 4, name: "topic", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 5, name: "total_length", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 6, name: "attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 7, name: "text_header", kind: "message", T: DataStream_TextHeader, oneof: "content_header" },
    { no: 8, name: "byte_header", kind: "message", T: DataStream_ByteHeader, oneof: "content_header" },
  ],
  {localName: "DataStream_Header"},
);

/**
 * @generated from message livekit.proto.DataStream.Chunk
 */
const DataStream_Chunk = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStream.Chunk",
  () => [
    { no: 1, name: "stream_id", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "chunk_index", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 3, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */, req: true },
    { no: 4, name: "version", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 5, name: "iv", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
  ],
  {localName: "DataStream_Chunk"},
);

/**
 * @generated from message livekit.proto.DataStream.Trailer
 */
const DataStream_Trailer = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStream.Trailer",
  () => [
    { no: 1, name: "stream_id", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 3, name: "attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
  {localName: "DataStream_Trailer"},
);

/**
 * @generated from message livekit.proto.DataStreamHeaderReceived
 */
const DataStreamHeaderReceived = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStreamHeaderReceived",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "header", kind: "message", T: DataStream_Header, req: true },
  ],
);

/**
 * @generated from message livekit.proto.DataStreamChunkReceived
 */
const DataStreamChunkReceived = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStreamChunkReceived",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "chunk", kind: "message", T: DataStream_Chunk, req: true },
  ],
);

/**
 * @generated from message livekit.proto.DataStreamTrailerReceived
 */
const DataStreamTrailerReceived = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataStreamTrailerReceived",
  () => [
    { no: 1, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 2, name: "trailer", kind: "message", T: DataStream_Trailer, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamHeaderRequest
 */
const SendStreamHeaderRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamHeaderRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "header", kind: "message", T: DataStream_Header, req: true },
    { no: 3, name: "destination_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "sender_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 5, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamChunkRequest
 */
const SendStreamChunkRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamChunkRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "chunk", kind: "message", T: DataStream_Chunk, req: true },
    { no: 3, name: "destination_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "sender_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 5, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamTrailerRequest
 */
const SendStreamTrailerRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamTrailerRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "trailer", kind: "message", T: DataStream_Trailer, req: true },
    { no: 3, name: "destination_identities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "sender_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
    { no: 5, name: "request_async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamHeaderResponse
 */
const SendStreamHeaderResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamHeaderResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamChunkResponse
 */
const SendStreamChunkResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamChunkResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamTrailerResponse
 */
const SendStreamTrailerResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamTrailerResponse",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamHeaderCallback
 */
const SendStreamHeaderCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamHeaderCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamChunkCallback
 */
const SendStreamChunkCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamChunkCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SendStreamTrailerCallback
 */
const SendStreamTrailerCallback = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SendStreamTrailerCallback",
  () => [
    { no: 1, name: "async_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message livekit.proto.SetDataChannelBufferedAmountLowThresholdRequest
 */
const SetDataChannelBufferedAmountLowThresholdRequest = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetDataChannelBufferedAmountLowThresholdRequest",
  () => [
    { no: 1, name: "local_participant_handle", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 2, name: "threshold", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
    { no: 3, name: "kind", kind: "enum", T: proto2.getEnumType(DataPacketKind), req: true },
  ],
);

/**
 * @generated from message livekit.proto.SetDataChannelBufferedAmountLowThresholdResponse
 */
const SetDataChannelBufferedAmountLowThresholdResponse = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.SetDataChannelBufferedAmountLowThresholdResponse",
  [],
);

/**
 * @generated from message livekit.proto.DataChannelBufferedAmountLowThresholdChanged
 */
const DataChannelBufferedAmountLowThresholdChanged = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.DataChannelBufferedAmountLowThresholdChanged",
  () => [
    { no: 1, name: "kind", kind: "enum", T: proto2.getEnumType(DataPacketKind), req: true },
    { no: 2, name: "threshold", kind: "scalar", T: 4 /* ScalarType.UINT64 */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.ByteStreamOpened
 */
const ByteStreamOpened = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.ByteStreamOpened",
  () => [
    { no: 1, name: "reader", kind: "message", T: OwnedByteStreamReader, req: true },
    { no: 2, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);

/**
 * @generated from message livekit.proto.TextStreamOpened
 */
const TextStreamOpened = /*@__PURE__*/ proto2.makeMessageType(
  "livekit.proto.TextStreamOpened",
  () => [
    { no: 1, name: "reader", kind: "message", T: OwnedTextStreamReader, req: true },
    { no: 2, name: "participant_identity", kind: "scalar", T: 9 /* ScalarType.STRING */, req: true },
  ],
);


exports.IceTransportType = IceTransportType;
exports.ContinualGatheringPolicy = ContinualGatheringPolicy;
exports.ConnectionQuality = ConnectionQuality;
exports.ConnectionState = ConnectionState;
exports.DataPacketKind = DataPacketKind;
exports.ConnectRequest = ConnectRequest;
exports.ConnectResponse = ConnectResponse;
exports.ConnectCallback = ConnectCallback;
exports.ConnectCallback_ParticipantWithTracks = ConnectCallback_ParticipantWithTracks;
exports.ConnectCallback_Result = ConnectCallback_Result;
exports.DisconnectRequest = DisconnectRequest;
exports.DisconnectResponse = DisconnectResponse;
exports.DisconnectCallback = DisconnectCallback;
exports.PublishTrackRequest = PublishTrackRequest;
exports.PublishTrackResponse = PublishTrackResponse;
exports.PublishTrackCallback = PublishTrackCallback;
exports.UnpublishTrackRequest = UnpublishTrackRequest;
exports.UnpublishTrackResponse = UnpublishTrackResponse;
exports.UnpublishTrackCallback = UnpublishTrackCallback;
exports.PublishDataRequest = PublishDataRequest;
exports.PublishDataResponse = PublishDataResponse;
exports.PublishDataCallback = PublishDataCallback;
exports.PublishTranscriptionRequest = PublishTranscriptionRequest;
exports.PublishTranscriptionResponse = PublishTranscriptionResponse;
exports.PublishTranscriptionCallback = PublishTranscriptionCallback;
exports.PublishSipDtmfRequest = PublishSipDtmfRequest;
exports.PublishSipDtmfResponse = PublishSipDtmfResponse;
exports.PublishSipDtmfCallback = PublishSipDtmfCallback;
exports.SetLocalMetadataRequest = SetLocalMetadataRequest;
exports.SetLocalMetadataResponse = SetLocalMetadataResponse;
exports.SetLocalMetadataCallback = SetLocalMetadataCallback;
exports.SendChatMessageRequest = SendChatMessageRequest;
exports.EditChatMessageRequest = EditChatMessageRequest;
exports.SendChatMessageResponse = SendChatMessageResponse;
exports.SendChatMessageCallback = SendChatMessageCallback;
exports.SetLocalAttributesRequest = SetLocalAttributesRequest;
exports.AttributesEntry = AttributesEntry;
exports.SetLocalAttributesResponse = SetLocalAttributesResponse;
exports.SetLocalAttributesCallback = SetLocalAttributesCallback;
exports.SetLocalNameRequest = SetLocalNameRequest;
exports.SetLocalNameResponse = SetLocalNameResponse;
exports.SetLocalNameCallback = SetLocalNameCallback;
exports.SetSubscribedRequest = SetSubscribedRequest;
exports.SetSubscribedResponse = SetSubscribedResponse;
exports.GetSessionStatsRequest = GetSessionStatsRequest;
exports.GetSessionStatsResponse = GetSessionStatsResponse;
exports.GetSessionStatsCallback = GetSessionStatsCallback;
exports.GetSessionStatsCallback_Result = GetSessionStatsCallback_Result;
exports.VideoEncoding = VideoEncoding;
exports.AudioEncoding = AudioEncoding;
exports.TrackPublishOptions = TrackPublishOptions;
exports.IceServer = IceServer;
exports.RtcConfig = RtcConfig;
exports.RoomOptions = RoomOptions;
exports.TranscriptionSegment = TranscriptionSegment;
exports.BufferInfo = BufferInfo;
exports.OwnedBuffer = OwnedBuffer;
exports.RoomEvent = RoomEvent;
exports.RoomInfo = RoomInfo;
exports.OwnedRoom = OwnedRoom;
exports.ParticipantsUpdated = ParticipantsUpdated;
exports.ParticipantConnected = ParticipantConnected;
exports.ParticipantDisconnected = ParticipantDisconnected;
exports.LocalTrackPublished = LocalTrackPublished;
exports.LocalTrackUnpublished = LocalTrackUnpublished;
exports.LocalTrackSubscribed = LocalTrackSubscribed;
exports.TrackPublished = TrackPublished;
exports.TrackUnpublished = TrackUnpublished;
exports.TrackSubscribed = TrackSubscribed;
exports.TrackUnsubscribed = TrackUnsubscribed;
exports.TrackSubscriptionFailed = TrackSubscriptionFailed;
exports.TrackMuted = TrackMuted;
exports.TrackUnmuted = TrackUnmuted;
exports.E2eeStateChanged = E2eeStateChanged;
exports.ActiveSpeakersChanged = ActiveSpeakersChanged;
exports.RoomMetadataChanged = RoomMetadataChanged;
exports.RoomSidChanged = RoomSidChanged;
exports.ParticipantMetadataChanged = ParticipantMetadataChanged;
exports.ParticipantAttributesChanged = ParticipantAttributesChanged;
exports.ParticipantEncryptionStatusChanged = ParticipantEncryptionStatusChanged;
exports.ParticipantNameChanged = ParticipantNameChanged;
exports.ParticipantPermissionChanged = ParticipantPermissionChanged;
exports.ConnectionQualityChanged = ConnectionQualityChanged;
exports.UserPacket = UserPacket;
exports.ChatMessage = ChatMessage;
exports.ChatMessageReceived = ChatMessageReceived;
exports.SipDTMF = SipDTMF;
exports.DataPacketReceived = DataPacketReceived;
exports.TranscriptionReceived = TranscriptionReceived;
exports.ConnectionStateChanged = ConnectionStateChanged;
exports.Connected = Connected;
exports.Disconnected = Disconnected;
exports.Reconnecting = Reconnecting;
exports.Reconnected = Reconnected;
exports.TokenRefreshed = TokenRefreshed;
exports.RoomEOS = RoomEOS;
exports.DataStream = DataStream;
exports.DataStream_OperationType = DataStream_OperationType;
exports.DataStream_TextHeader = DataStream_TextHeader;
exports.DataStream_ByteHeader = DataStream_ByteHeader;
exports.DataStream_Header = DataStream_Header;
exports.DataStream_Chunk = DataStream_Chunk;
exports.DataStream_Trailer = DataStream_Trailer;
exports.DataStreamHeaderReceived = DataStreamHeaderReceived;
exports.DataStreamChunkReceived = DataStreamChunkReceived;
exports.DataStreamTrailerReceived = DataStreamTrailerReceived;
exports.SendStreamHeaderRequest = SendStreamHeaderRequest;
exports.SendStreamChunkRequest = SendStreamChunkRequest;
exports.SendStreamTrailerRequest = SendStreamTrailerRequest;
exports.SendStreamHeaderResponse = SendStreamHeaderResponse;
exports.SendStreamChunkResponse = SendStreamChunkResponse;
exports.SendStreamTrailerResponse = SendStreamTrailerResponse;
exports.SendStreamHeaderCallback = SendStreamHeaderCallback;
exports.SendStreamChunkCallback = SendStreamChunkCallback;
exports.SendStreamTrailerCallback = SendStreamTrailerCallback;
exports.SetDataChannelBufferedAmountLowThresholdRequest = SetDataChannelBufferedAmountLowThresholdRequest;
exports.SetDataChannelBufferedAmountLowThresholdResponse = SetDataChannelBufferedAmountLowThresholdResponse;
exports.DataChannelBufferedAmountLowThresholdChanged = DataChannelBufferedAmountLowThresholdChanged;
exports.ByteStreamOpened = ByteStreamOpened;
exports.TextStreamOpened = TextStreamOpened;
