name: Install Common Deps for UniFFI Tasks
runs:
  using: composite
  steps:
    - name: Install cargo-make
      uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
      with: { tool: cargo-make@0.37 }
